### ISSUE TITLE
Fix Battery volts sensor unit of measurements

### ISSUE THREAD

**Issue by chertvl** [tolwi/hassio-ecoflow-cloud#100]
Found that unit of measurements of Battery Volts sensor is uncorrect.
It displays "26 mV", but there is 26 volts.
If you have some free minute, please change "mV" unit (wich pulled for all voltage sensors)  to just "V".
This is the only sensor where this unit of measurement does not fit.

P.S.:  Yup, I can easily do that with customization, but we prefer the right solutions to problems, right? ;)

River 2 Max, fw: v4.1.1.56 + v.2.1.2.26(wifi).
Thank you!

![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/38353584/7065cca4-c192-42f4-ad95-fa33acd38a2d)

**Comment by mattwells** [comment]
Is that cell voltage or pack voltage because it if is cell voltage that would be 2.6v just to add to the confusion

**Comment by chertvl** [comment]
> Is that cell voltage or pack voltage because it if is cell voltage that would be 2.6v just to add to the confusion.
> 
> I can confirm that the Battery Volts, Min Cell Volts and Max Cell Volts are all correct for the Delta Pro.

For my River 2 Max its  8x  3.3v  = ~26V
and for example 8x 3.6v = ~29V when charging

**Comment by tolwi** [comment]
looks like only River2 family reports total battery voltage in volt, all other devices reports millivolts
