### ISSUE TITLE
Charging state binary_sensor

### ISSUE THREAD

**Issue by tolwi** [tolwi/hassio-ecoflow-cloud#109]
May I ask you also to add sensor or binary_sensor for charging state?
Got it:   
"bms_emsStatus.chgState": 1,
1 - is charging, 0 - is not charging internal battery.

So far I have written an automation in which I determine the **fact of the charging** using of the charging remaining time sensor state != 0  
😀

_Originally posted by @chertvl in https://github.com/tolwi/hassio-ecoflow-cloud/issues/99#issuecomment-1656893439_

**Comment by tolwi** [comment]
River2 family (`bms_emsStatus.chgState`): present, valid
Delta2 family (`bms_emsStatus.chgState`): present, invalid (always On)
River family: not present
Delta family: not present

**Comment by chertvl** [comment]
@tolwi 
This works great!
Thank you very much for the implementation of the necessary for all my requests!

**Comment by chertvl** [comment]
> River2 family (`bms_emsStatus.chgState`): present, valid

Ive made a little mistake,  ```chgState``` is not a binary.
I have also   ```"bms_emsStatus.chgState": 2,``` state when internal battery is discharging.
In implementation of https://github.com/tolwi/hassio-ecoflow-cloud/commit/dc4151bf44213490e1dde6882b53734a874d64ef
HA Sensor is always  ```on``` if battery is charging or discharging, and ```of``` if unused.

Can we improve it? Possible variants:
a) 2 separate sensors:  1) value == 1 ? 'on' : 'off'  (for charging sensor), and 2) value == 2 ? 'on' : 'off' (for discharging sensor)
b) 1 common text sensor with possible states "unused, charging, discharging, (unknown, unavailable)".
