### ISSUE TITLE
Tesla Power Card

### ISSUE THREAD

**Issue by neotigger** [tolwi/hassio-ecoflow-cloud#11]
For users of the Delta2 with additional battery and the Tesla Power card , the value "bms_emsStatus.lcdShowSoc" would be of interest, as it contains the combined value of both batteries.

To use it in the Tesla Power map as an additional entity for the battery symbol
![IMG_5493](https://user-images.githubusercontent.com/121525065/216788202-2217d40e-f65b-4e3a-9343-dcf0b7900247.jpeg)
![Bildschirmfoto 2](https://user-images.githubusercontent.com/121525065/216788212-98e38174-2362-4c6b-945e-ca1565f39a6b.png)

**Comment by tolwi** [comment]
check v0.7.1
