### ISSUE TITLE
DeltaMax 2 Only showing one Solar Input

### ISSUE THREAD

**Issue by digitalurban** [tolwi/hassio-ecoflow-cloud#111]
This is minor but perhaps worth flagging - the feed from the Delta Max 2 only shows Solar from one of the inputs. Total Power does show the combination of both the solar sockets but it does not seem possible to get data from Solar 1 and Solar 2 independently.

A great intergration though, really appreciated.

Andy

**Comment by tolwi** [comment]
v0.13.1
