### ISSUE TITLE
RIVER 2 Integration

### ISSUE THREAD

**Issue by lippi00** [tolwi/hassio-ecoflow-cloud#12]
Support for the River 2 would be very appreciated - Diagnostics attached.
Cheers an best wishes to Ukraine!
[config_entry-ecoflow_cloud-ebc77b643d995eb317340a43b694fa55.json.txt](https://github.com/tolwi/hassio-ecoflow-cloud/files/10678303/config_entry-ecoflow_cloud-ebc77b643d995eb317340a43b694fa55.json.txt)

**Comment by yuralcfr** [comment]
+1

**Comment by tolwi** [comment]
Try to fulfill this issue with info according to the following [notes](https://github.com/tolwi/hassio-ecoflow-cloud/blob/main/docs/integration.md)

**Comment by lippi00** [comment]
I had a look and compared to RIVER 2 Max Specs - Sensors and Switches look good. The AC Charge Speed Slider can only be adjusted between 100-360 Watts.

AC Charging Power (mppt.cfgChgWatts -> {"moduleType": 5, "operateType": "acChgCfg", "params": {"chgWatts": "VALUE", "chgPauseFlag": 255}} [100 - 360])

And I've got another Select to offer.

DC Mode (mppt.cfgChgType -> {"moduleType": 5, "operateType": "chaType", "params": {"chaType": "VALUE"}} [Automatic (0), Solar Recharging (1), Car Recharging (2)])

**Comment by lippi00** [comment]
I tested 'DC Mode' (v0.8.1) - Perfect, works and syncs both ways. 

I notized that Power of both USB-A Ports (the small RIVER 2 has only two) are being summarized under "pd.usb1Watts". That means there is no need for entity "sensor.ecofl_usb_2_out_power", value is always zero. Personally I don't mind it being there - since "pd.usb2Watts" is actually present in API / diagnostics export.
