### ISSUE TITLE
Delta Max AC-Ladeleistung Regler hat keine Funktion

### ISSUE THREAD

**Issue by jeff1975** [tolwi/hassio-ecoflow-cloud#126]
Delta Max AC-Ladeleistung Regler hat keine Funktion "Range von 200-2000 W in 100W Schritte wäre perfekt"
und max. Ladezustand 0–100 %. Ladezustand hat bei Delta max auch keine Funktion

**Comment by DSRocker** [comment]
Gibt es jetzt.
