### ISSUE TITLE
How to update integration on existing entities?

### ISSUE THREAD

**Issue by moehringn** [tolwi/hassio-ecoflow-cloud#13]
Hi there,

I installed integration with v0.5.0 and everything ist working fine. Yesterday I updated to 0.7.1, but the new entities from version 0.6.0 (typec1Watts, usb1Watts, etc.) are not showing up.

My update process is as follows:

1. HACS > integrations > EcoFlow Cloud
2. 3-dot menu at the top right > redownload
3. select version to install > Download
4. restart Home Assistant

Home Assistant (and core) are on the latest version.
I have two Delta 2, one with the addition battery. Do I have to remove the devices and add them again?

I'm currently loading 2 smartphones on USB and TypeC ports as I thought the properties might have to change to be send via mqtt, but the entities are still not showing up.

Thank you for your advice.

Best regards
Norbert

**Comment by tolwi** [comment]
> 3-dot menu at the top right > redownload
try "Update Information" instead - Home Assistant will notify you if there is a new version available to install

**Comment by raphaelsavina** [comment]
Same here with v0.7.2, tried `redownload`, `Update Information` and also remove/restart HA/re-install and didn't give me all the new entities.
Any cache to be renoved?

**Comment by raphaelsavina** [comment]
Fixed that by deleted the old folder /ecoflow_cloud in /custom_components (look at manifest.json to see which one is the old one).

**Comment by moehringn** [comment]
Worked with the last updates.
