### ISSUE TITLE
Delta 2 Max - switch to enable AC not working

### ISSUE THREAD

**Issue by bogdancs92** [tolwi/hassio-ecoflow-cloud#133]
The AC can't be enabled via l'addon on the Delta 2 MAX.
It is working on Delta 2.
Anyone has the same problem ?

**Comment by KagasiraBunJee** [comment]
Hi, i also encountered issue where i cannot turn on/off AC on Delta 2 Max

I attached logs

[config_entry-ecoflow_cloud-3024591f5e3c695f2d5e9dbb3e1617f2.json.txt](https://github.com/tolwi/hassio-ecoflow-cloud/files/12480292/config_entry-ecoflow_cloud-3024591f5e3c695f2d5e9dbb3e1617f2.json.txt)

**Comment by DerBaer1986** [comment]
Inhaber the same Problem. 
I am using the forked Version from @faken.

https://github.com/tolwi/hassio-ecoflow-cloud/issues/60#issuecomment-1653504585

**Comment by DauntlessEagle** [comment]
I still also have this same issue, let me know what info to provide to help resolve the issue. AC does not turn on, AC always on and ac charging power all do not work for me. Thank you.

**Comment by odaigle** [comment]
Same here. The "Delat2Max AC enable" can't be used to enable/disable the AC output, although the switch is properly representing the status when changing the AC output in the Ecoflow app or with the physical button on the unit.

**Comment by odaigle** [comment]
I can't say I am understanding everything that I did, but I managed to make the AC enable/disable switch work by changing delta2_max.py with the following:

            EnabledEntity(client, "inv.cfgAcEnabled", const.AC_ENABLED,
                          lambda value: {"moduleType": 3, "operateType": "acOutCfg",
                                         "moduleSn": client.device_sn,
                                         "params": {"enabled": value, "out_voltage": -1, "out_freq": 255,
                                                    "xboost": 255}}),
#                          lambda value: {"moduleType": 3, "operateType": "acOutCfg",
#                                         "moduleSn": client.device_sn,
#                                         "params": {"enabled": value}}),

I tried to modify the xboost switch in the same way, but it is not working.

**Comment by marcuslib** [comment]
Yeah, i can confirm that its not working for me either, it works on the delta 2 but not the delta 2 max

**Comment by tolwi** [comment]
v0.13.0
