### ISSUE TITLE
[Question] Powerstream - Mode (Storage or Supply AC Output) already available?

### ISSUE THREAD

**Issue by giovanne123** [tolwi/hassio-ecoflow-cloud#138]
Question, is the mode of Powerstream - if he is in storage mode to Delta 2 Max or power supply mode to AC output already available in the Powerstream sensors/HA entities coming from ecoflow_cloud integration?

So far I can't find it or maybe I overseen the naming?

Thanks

**Comment by nealjane** [comment]
This would be good if possible - as we could then alter PS mode if eg battery is 50% full etc

**Comment by DauntlessEagle** [comment]
I third this, this would be highly useful if we had this feature

**Comment by danroth77** [comment]
I would also love to have this feature.

**Comment by mattwells** [comment]
I would very much like to do that but it requires a fairly significant change to the way the integration works because the PowerStream uses a different way of encoding the messages to what previous Ecoflow devices have done. I need the time to invest to learn enough Python and Home Assistant to be able to do it.

I am aware that others have managed to get a work around using IOBroker but I haven't tried it myself https://github.com/tolwi/hassio-ecoflow-cloud/issues/54#issuecomment-1657073208

**Comment by giovanne123** [comment]
Right. 
Initially my intention in this issue was only the question if the current state of Powerstream mode (AC Output or storage) is available in existing entities (ready only) because I can't find it 😉

For the extended feature to control it actively, in the meantime (until Ecoflow Cloud integration isn't able to control that) I use the  nodejs (https://github.com/bogdancs92/ecoflow-powerstream-nodejs) standalone solution which was derived from the iobroker script.
My way: https://github.com/giovanne123/Ecoflow_Powerstream_HomeAssistant_Automation_Documentation/blob/main/README.md

**Comment by NameIstSchonVergeben** [comment]
Same problem - but there is a way to switch between AC and storage using a Shelly.

My Powerstrem runs over an AC line that is interrupted with a Shelly (for more precise recording of the values).

When the Shelly disconnects from the grid, the PowerStream automatically feeds into the storage, as the power has nowhere else to go, even if the grid is prioritized in the app.

With automation you can configure the Shelly to disconnect when the storage only has xx% left. So long no better Way exist.....

But in the Moment there ist a Problem when nighttime beginns / ends - the Powerstream stay on and use Power from the Battery - so the Battery also stay online. In the Morning when the Sun goes to the Paneels the Powerstream not aktivate the Paneelpower to the grid (when Shelly is ON) or to the Battery - I have to switch off Delta Pro and Powerstream / disconnect from Solar and grid and restart - after this it works - the Ecoflow Technik works on this Problem and they want fix it with the next Updates

**Comment by giovanne123** [comment]
From my side this was initial only a question. Question answer is not so far.
No longer needed from my side because  Ecoflow API is available and I will go that way using http requests...
