### ISSUE TITLE
[Feature Request] Battery mAh attributes as Sensors

### ISSUE THREAD

**Issue by Ne0-Hack3r** [tolwi/hassio-ecoflow-cloud#139]
I've created custom sensors to provide battery capacity data (Full vs Remaining) for DP, D2, D2M in a form that can be recorded, accessed in History, and more easily integrated on the dashboard. I realize many may not care about these particular readings but I find them informative in terms of understanding calibration and also observing when the full capacity counter, in particular, is altered (this is particularly strange for DP at times).

In any case, I was wondering if there are better ways to handle the data while continuing to have it as an attribute (of the main battery level, for example) or if there is interest (and/or willingness on the part of @tolwi) to consider having these as actual sensors rather than attributes within the integration itself. I'm also interested to know if there are particular reasons this data was treated as attributes in the first place.

**Comment by knyghtryda** [comment]
This could be really useful, though in its current state I feel like its perfectly functional, minus history data.  I'm currently using this info to automatically run a calibration cycle (drain to near empty, charge to full) when the "full capacity" decreases below 60Ah.  I have a smart plug on the AC in to handle this, and it will turn charging back on when battery voltage gets below 47v (which is close enough to 0% charge for me).  I'm really not sure why the DP has such a wonky calibration, as the Delta 2 doesn't suffer from the same issue (I cycle my delta 2 regularly between 50% and 85%, and it never seems to lose full battery capacity).

**Comment by Ne0-Hack3r** [comment]
> This could be really useful, though in its current state I feel like its perfectly functional, minus history data. I'm currently using this info to automatically run a calibration cycle (drain to near empty, charge to full) when the "full capacity" decreases below 60Ah. I have a smart plug on the AC in to handle this, and it will turn charging back on when battery voltage gets below 47v (which is close enough to 0% charge for me). I'm really not sure why the DP has such a wonky calibration, as the Delta 2 doesn't suffer from the same issue (I cycle my delta 2 regularly between 50% and 85%, and it never seems to lose full battery capacity).

@knyghtryda - are you seeing the full Ah counter reset to 76Ah after cycling like that? I have never observed it correct itself (at least not as of .49 firmware and prior). I've always had to do a BMS reset immediately at the top.

**Comment by knyghtryda** [comment]
@Ne0-Hack3r Nope, never saw the full capacity.  If I fully cycle multiple times the full capacity increases, but I've only cycled twice in a row. I think I've gotten close to 70Ah.

**Comment by tolwi** [comment]
v0.13.0
