### ISSUE TITLE
Solar in Delta2 Max

### ISSUE THREAD

**Issue by Milchbeck** [tolwi/hassio-ecoflow-cloud#143]
Solar in only one Panel but the Delta 2 Max can two and I have two's on it but only one can I see the Watt's 

Can you fix it?

Lg
Tom

**Comment by tolwi** [comment]
Attach diagnostic data, please

**Comment by Milchbeck** [comment]
I mean the Solar in for Delta2Max has two mppt tracker but die Integration have only one MPPT (Solar_In)

**Comment by tolwi** [comment]
> How I can do this
https://www.home-assistant.io/integrations/diagnostics/

**Comment by Milchbeck** [comment]
![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/129594234/a8f08dbb-2b08-4682-930e-1d8fc0a917d4)

![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/129594234/b05c1db2-b629-40ea-b0c9-7bf4a48dcb3d)

**Comment by cpc989** [comment]
I looked at this a while back I believe the

Solar 1 is "mppt.inWatts"
Solar 2 is "mppt.pv2inWatts"

**Comment by DauntlessEagle** [comment]
Any progress on this? only able to track one of my solar panels currently, does not show the watts on the 2nd input.

**Comment by odaigle** [comment]
I guess I'll run into the same issue pretty soon as I am planning on attaching solar panels to both inputs of the PV Delta2Max. Here are the diagnostics from the unit:

[config_entry-ecoflow_cloud-77516e3d49f228fedf6e501864be63ac.json.txt](https://github.com/tolwi/hassio-ecoflow-cloud/files/12770651/config_entry-ecoflow_cloud-77516e3d49f228fedf6e501864be63ac.json.txt)

**Comment by MicStable** [comment]
I can only confirm the problem and would be happy if the second tracker could also be integrated.

**Comment by giovanne123** [comment]
@tolwi , thank you very much for implementing 👍

**Comment by Milchbeck** [comment]
![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/129594234/1ed90d26-a1b1-4c46-9a91-e0a6e00fca59)


I don't see Solar in 2

**Comment by giovanne123** [comment]
After updating to 0.12.3 I have re-added Delta 2 Max and then sensor.delta_2_max_solar_1_in_power and sensor.delta_2_max_solar_2_in_power are available.
