### ISSUE TITLE
The Staus frize from all Ecoflow Delta2Max River2pro and Powerstream

### ISSUE THREAD

**Issue by Milchbeck** [tolwi/hassio-ecoflow-cloud#151]
![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/129594234/4a96eec5-9787-4944-a154-1e8c065effb8)![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/129594234/a32b78ec-34ef-4af0-a50e-9f35ec74a2c4)

Only when I restarted the integration works again

**Comment by tolwi** [comment]
not enough info here, but I assume it is the same problem as in #153
