### ISSUE TITLE
"AC Charging Power" not work

### ISSUE THREAD

**Issue by electroromano** [tolwi/hassio-ecoflow-cloud#167]
Hello @tolwi 

The entity "AC Charging Power"  in the "Configuration" menu not work :
![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/143942281/a51a041a-1b0d-4f0c-8795-4862294b1c8f)

On the application this parameter is set to "200W" and they not synchronize with this entity, and the modification of the entity is not taken into account either.

Can you check this ?

Thanks

**Comment by electroromano** [comment]
Hi,
For additional information, 
In the smartphone application the limits are from 200W to 2000W with thresholds of 100W while the Home Assistant application the limits are from 400W to 2200W with thresholds of 100W also. 

Can you apply the same value as the official Ecoflow smartphone application ?

THANKS for all

**Comment by electroromano** [comment]
Hi again @tolwi ,

I notice another anomaly, the entity "Battery Max Chage Level" not work perfecty too
![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/143942281/73d83cf7-5975-4b96-b6d2-35640f2385d1)

Not work for control, just for reading.
If i set 50% after 2s the velue back to the last value coresponding in the smartphone application.

If i can help you i use an ECOFLOW Delta MAX v1.6.2.52 and soon v1.6.2.71
I hope you can fix these things

Thanks

**Comment by electroromano** [comment]
Hello @tolwi 
I think it's the same issue on the #159 can you merge with my issue ?
For Aditional information the update of DELTA MAX is done (v1.6.2.71) but this does not correct the problem.
Thanks

**Comment by not4rthur** [comment]
Hi, I found a workaround and posted it in #159 .

Cheers

**Comment by electroromano** [comment]
Solved by @not4rthur in #159
