### ISSUE TITLE
Link to Energy Dashboard not possible

### ISSUE THREAD

**Issue by juliusjac** [tolwi/hassio-ecoflow-cloud#168]
Hi there,
here is the link that should be provided to the Author:
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

Source:
https://www.home-assistant.io/more-info/statistics/

**Comment by electroromano** [comment]
Hi @juliusjac,

i think you need to use : https://www.home-assistant.io/integrations/integration/
( Integration - Riemann sum integral )
and chose the Entity "..._power" for create the new entity usable in the energy dashboard

**Comment by juliusjac** [comment]
Thanks for the quick response! This fixed the problem.
