### ISSUE TITLE
Min Discharge Level not work

### ISSUE THREAD

**Issue by Scan4u** [tolwi/hassio-ecoflow-cloud#17]
Hi! Found a small issue with the Min Discharge Level selector. 
After the adjusting, it does not fix the new value, and returns to the old position.
Made a small video for describe - please [check it](https://youtube.com/shorts/8BSibOvj7IU)

**Comment by Katzi1986** [comment]
Hello, I have observed the same behavoiur with my Delta2.

**Comment by tolwi** [comment]
should be fixed in v0.7.5

**Comment by Scan4u** [comment]
Thank U! Just checked the v0.7.5 - working perfect! Good job!
