### ISSUE TITLE
Slave battery not showing

### ISSUE THREAD

**Issue by sirdir1972** [tolwi/hassio-ecoflow-cloud#172]
Hi!
I don’t get any info for my slave battery. As I’ve seen the same problem with another implementation, maybe you’re expecting a different path where the data is to be found. In my case it’s ‘bms_slave_bmsSlaveStatus_1’ on a Delta 2 Max.

**Comment by sirdir1972** [comment]
I found out the slave battery is completely commented out… so no wonder why it doesn't show the correct data. 
Anyways, after putting the path I mentioned in the last message in, it works. Also, there's another important value: 

 LevelSensorEntity(client, "bms_bmsStatus.soh", const.SOH),

State of health.

**Comment by tolwi** [comment]
@sirdir1972 attach the diagnostic dump please

**Comment by sirdir1972** [comment]
OK, but keep in mind I changed your integration. I removed the commented out parts and added lines for SOH
[config_entry-ecoflow_cloud-f3bdfc7fd62690ba42d13db36784d4f4.json.txt](https://github.com/tolwi/hassio-ecoflow-cloud/files/13849757/config_entry-ecoflow_cloud-f3bdfc7fd62690ba42d13db36784d4f4.json.txt)

**Comment by tolwi** [comment]
well, maybe you can create a PR with your changes?

**Comment by sirdir1972** [comment]
PR? push? Sorry I'm not that much into github.

**Comment by sirdir1972** [comment]
Here are the files I changed. the slave battery isn't commented out anymore, so if you want to use it, take that in mind. I updated the changes for the slave batteries that were missing (missing comma, volt instead of millivolts etc) 
[changes.zip](https://github.com/tolwi/hassio-ecoflow-cloud/files/13881723/changes.zip)
