### ISSUE TITLE
River2Max not accessible after firmware update V4.1.1.58

### ISSUE THREAD

**Issue by sporttiger1000** [tolwi/hassio-ecoflow-cloud#176]
I cannot access my River2 Max anymore after updating to firmware V4.1.1.58 and V2.1.4.31WLAN. All values do not update anymore and I cannot control the device. Anyone having similar issues?

**Comment by tolwi** [comment]
I have just checked mine river2max with the same firmware - everything works fine.

**Comment by sporttiger1000** [comment]
I added the device once again and it is working. Sorry!
