### ISSUE TITLE
Adding bms_slave ?

### ISSUE THREAD

**Issue by raphaelsavina** [tolwi/hassio-ecoflow-cloud#2]
More a feature request than a bug. Would it be possible to add the 2nd battery data (Exta Delta2).
The main thing is that the soc is likely to be different from the soc of the main battery so I would like to check both or do an average.

Here is from my diagnostics:
      {
        "id": xxx,
        "version": "1.0",
        "timestamp": 1674729556,
        "moduleType": "4",
        "params": {
          "bms_slave.temp": 13,
          "bms_slave.minCellVol": 3308,
          "bms_slave.outputWatts": 0,
          "bms_slave.f32ShowSoc": 96.1,
          "bms_slave.soc": 96,
          "bms_slave.minCellTemp": 13,
          "bms_slave.inputWatts": 0
        }
      },

Happy to send you my full diagnostic if that helps.

Thanks
Raphaël

**Comment by raphaelsavina** [comment]
Diagnostic for Extra Delta2 battery, seems like plenty of entries with `slave` 

[config_entry-ecoflow-cloud-8522bea4861e8c7bd798add3b33882a6.json.txt](https://github.com/tolwi/hassio-ecoflow-cloud/files/10508546/config_entry-ecoflow-cloud-8522bea4861e8c7bd798add3b33882a6.json.txt)

**Comment by tolwi** [comment]
try version 0.4.0 (latest commit)

**Comment by tolwi** [comment]
@raphaelsavina is it ok - can I close this issue?
