### ISSUE TITLE
ChargingPowerEntity at _attr_native_step = 100?

### ISSUE THREAD

**Issue by raphaelsavina** [tolwi/hassio-ecoflow-cloud#20]
Hi, 

Any reason why you needed to change this from 1 in older version to the ecolflow 100W (for Delta2)?

I liked the old version with 1W slider (or even 10W would do) as it help me use extra W produced by my solar panels (with microinverter so at 220V) to inject into the Delta2. 

Thanks
Raphaël

**Comment by tolwi** [comment]
no reason - will fix that

**Comment by tolwi** [comment]
hm, checked in the app: you can drag the slider with 1% step, but it is rounded at the end. For delta 2 - rounded to 100, for river2max - to 50. Have just selected 488 for river and this value "comes back" in `mppt.cfgChgWatts` (assume that the value is ok for the device), but it looks like the native app cannot display that value so this change is not visible - the app still displays 550.
Not sure how to deal with this ...

**Comment by raphaelsavina** [comment]
In previous versions of your code it was working in HA, the fact that it is not reflected in the native app is not an issue for me as I don't need to open it if the integration in HA is working.

**Comment by tolwi** [comment]
It is ok for me also, but someone will definitely raise an issue on that :) 
Maybe it is better to add an additional control like 'charging power precision' with defaults to value from the app and the possibility to change it?

**Comment by raphaelsavina** [comment]
Yes, that would work. For now I have edited number.py for my usage, but it will be reverted at each new version.

**Comment by tolwi** [comment]
try v0.8.1

**Comment by tolwi** [comment]
it looks like it is just impossible to adjust by 1 using the mouse: in my case slider width is 168px for 1200 value :) 
Actually, you can adjust by 1 with the keyboard - drag with the mouse and then use up/down keys

**Comment by raphaelsavina** [comment]
Indeed, the arrow trick work and as it was to be used in automation at 1W increment, this is all good. I'll close this! 
Thank you.
