### ISSUE TITLE
Question: Does this integration communicate local with the Ecoflow or via internet?

### ISSUE THREAD

**Issue by Peronia** [tolwi/hassio-ecoflow-cloud#221]
Hi,

I'm new in the Ecoflow system, my River 2 Max is on the way :D
I don't understand if this integration communicate local (via MQTT) or over the internet with the Ecoflow powerstation (in general, not a specific one).
So my point of understanding is:

- The powerstation has a local MQTT service to report data
- Either the smartphone app or integrations like this can be used to get connect with the MQTT service, since the powerstation itself don't have access to the internet
  - So the app will connect with the local MQTT service and send the data to Ecoflow servers
  - Integrations like this will interact with the local MQTT service as well and don't send the data to Ecoflow servers, instead send them to Home Assistant in this case
- Only to get the MQTT credentials we need to talk with Ecoflow servers

Is that correct? I can imagine that the other way could be to ask always the Ecoflow servers for new data. This assumes that the MQTT data somehow gets from the powerstation to the Ecoflow servers. But it's not really clear to my how this could happen.

**Comment by Nid01** [comment]
Hello Peronia,
when you are using the smartphone app from EcoFlow then the EcoFlow products communicate either with the EcoFlow servers via MQTT and their servers with the app on your smartphone or directly via Bluetooth when your smartphone or the RIVER 2 Max in your case has no internet connection via WiFi.

**Comment by Peronia** [comment]
Okay @Nid01, thanks.
My powerstation arrived yet ant yeah, this integration is complete online, like:
powerstation -> (smartphone via Bluetooth) -> Ecoflow servers -> Home assistant
So I think it's more a replacement for the app in HA (thats not bad).

But I'm looking to ask the powerstation local if I have an outage (mainly ask if the accu get used). For that I can't use this integration, maybe other network devices have problems too (they mustn't be located in my household).
I found a [script](https://github.com/Netfreak25/EcoFlow_MQTT_Creds/blob/main/ecoflow_mqtt_creds.sh) to extract the MQTT credentials, is that used to comunicate local with the powerstation or onlne over the ecoflow servers (like this integration)?

**Comment by Nid01** [comment]
> I found a [script](https://github.com/Netfreak25/EcoFlow_MQTT_Creds/blob/main/ecoflow_mqtt_creds.sh) to extract the MQTT credentials, is that used to comunicate local with the powerstation or onlne over the ecoflow servers (like this integration)?
The credentials are used to communicate with the EcoFlow servers like this integration does.
There are two repositories on GitHub concerning the Bluetooth communication to the EcoFlow devices, but I have no clue how on how difficult it is to set this up.
https://github.com/avaver/ecoflow-ble
https://github.com/nielsole/ecoflow-bt-reverse-engineering

**Comment by Peronia** [comment]
Okay thanks. Makes sense, otherwise anyone could query the values with the serial number.
