### ISSUE TITLE
PowerStream "Other Loads (permanent_watts)" should be a number

### ISSUE THREAD

**Issue by vinch22** [tolwi/hassio-ecoflow-cloud#236]
Hi
I have been using EcoFlow Cloud Integration for Home Assistant
for a few month and it is great!

I recently bought a POWERSTREAM to connect to my DELTA_2_MAX,
and unfortunately something is missing...

The sensor "Other Loads (permanent_watts)" should be a number,
just like "AC Charging Power" for the DELTA_2_MAX for exemple.

These are the configurable values from the Ecoflow smartphone application : 
Minimum value : 0
Maximum value : 800
increment : 10

I understand that there are modifications to be made in the file : 
custom_components/ecoflow_cloud/devices/powerstream.py
(and probably elsewhere!)
but I'm not skilled enough to do them myself...

I hope this modification can be made quite easily?

Thanks,
Vincent.

**Comment by Nid01** [comment]
@vinch22 I guess you mean the we should be able to adjust how much power should go from the PowerStream into the net?
This is not supported via the mqtt api the integration uses.
@Mark-Hicks and I a separately working on creating a new integration which uses the new API from EcoFlow, there it will be possible to adjust the power output of the PowerStream.

**Comment by vinch22** [comment]
Ok thanks for your answer.
I'm looking forward for this future new integration.
