### ISSUE TITLE
Getting no data from the EcoFlow Cloud into the dashboard

### ISSUE THREAD

**Issue by Smarties202420** [tolwi/hassio-ecoflow-cloud#237]
Hi there,

sorry if it may is a super stupid question.
I just started to work with Home Assistant and the Hassio-ecoflow-cloud app 2 days ago.

To test the functionalities I made up a VM on my NAS, loaded HomeAssistant into it, added HACS, FileEditor and finaly the Hassio-Ecoflow-Cloud app. So far, so good.

Bad thing: I can not see any data coming in.

Running the debugging for a while, I get the following error log:

=========================================

2024-05-13 21:52:05.958 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-13 21:52:05.959 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration ecoflow_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-13 21:52:05.959 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration bosch_shc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-13 21:52:05.960 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-13 21:52:09.536 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-05-13 21:52:16.256 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

===========================================

I browsed for the two WARNINGS regarding HACS, but they do not feel related.

Is there anything I can do? E.g check to pin down the problem?

I already modified the PyScript with file editor according to[ this information](https://github.com/tolwi/hassio-ecoflow-cloud/issues/232)

No changes....

Some ideas what may causes my issue?

Thank you, KR,
Sascha

**Comment by Nid01** [comment]
You should have the option download diagnostics.
[image](https://private-user-images.githubusercontent.com/30300755/330166012-3e6e34cf-b9b8-45a8-aba5-68888b24202e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MzE3OTgsIm5iZiI6MTcxNTYzMTQ5OCwicGF0aCI6Ii8zMDMwMDc1NS8zMzAxNjYwMTItM2U2ZTM0Y2YtYjliOC00NWE4LWFiYTUtNjg4ODhiMjQyMDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDIwMTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYzFjNDYyMmFjMjMwNGYyNjRiODFhODViN2Y2ZWQyYmVlZWQxYzkxNGIyM2EyNjliN2FjYmZiMDc2MjM2ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zyVDot6Mgj11zCzhJAfCL5TqJfzZ0tDmuWPxbTfE9NI)

There you should be able to find data which contains the received messages from your device.
When you don't find that you might need to add the device as diagnostic so the raw messages get stored.
From that we could find out, what might be off in your situation.

**Comment by Smarties202420** [comment]
Hi @Nid01,

thanks for the swift reply.
When I dl this diagnostics, I get a JSON with this content:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.5.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.6.29-haos",
    "supervisor": "2024.05.1",
    "host_os": "Home Assistant OS 12.3",
    "docker_version": "25.0.5",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "pyscript": {
      "documentation": "https://github.com/custom-components/pyscript",
      "version": "1.5.0",
      "requirements": [
        "croniter==1.3.8",
        "watchdog==2.3.1"
      ]
    },
    "ecoflow_cloud": {
      "documentation": "https://github.com/tolwi/hassio-ecoflow-cloud",
      "version": "0.13.2",
      "requirements": [
        "paho-mqtt==1.6.1",
        "reactivex==4.0.4",
        "protobuf>=4.23.0"
      ]
    },
    "bosch_shc": {
      "documentation": "https://github.com/tschamm/boschshc-hass/blob/master/README.md",
      "version": "0.4.89",
      "requirements": [
        "boschshcpy==0.2.91"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "ecoflow_cloud",
    "name": "Ecoflow-Cloud",
    "codeowners": [
      "@tolwi"
    ],
    "config_flow": true,
    "documentation": "https://github.com/tolwi/hassio-ecoflow-cloud",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/tolwi/hassio-ecoflow-cloud/issues",
    "requirements": [
      "paho-mqtt==1.6.1",
      "reactivex==4.0.4",
      "protobuf>=4.23.0"
    ],
    "version": "0.13.2",
    "is_built_in": false
  },
  "data": {
    "device": "POWERSTREAM",
    "params": {},
    "set": [],
    "set_reply": [],
    "get": [],
    "get_reply": [],
    "raw_data": []
  }
}

**Comment by Nid01** [comment]
Maybe you got a typing error?
Please recheck you entered the correct serial number of your PowerStream.

**Comment by MrScotch72** [comment]
I have the same problem since yesterday.
Previously it worked for several weeks without any problems

**Comment by moovikafrance** [comment]
Same problem, No measurements or parameters available on Home Assistant Ecoflow cloud

**Comment by icygame** [comment]
Ditto. Stopped working in the last day.

**Comment by mariomodena** [comment]
Same problem, No Data from EcoflowCloud since yesterday!

**Comment by irvelervel** [comment]
Updated today to the latest home assistant (2024.5.3) and I can indeed confirm the same problem. It was working fine until this afternoon, while I was still on 2024.4.2.

**Comment by Nid01** [comment]
@MrScotch72  @moovikafrance @icygame @mariomodena @irvelervel 
I'm running home assistant version 2024.5.3 and ecoflow_cloud version 0.13.2 and sadly can't replicate your issues, are all of you only unable to receive data for the PowerStream or other devices too?
And can you please confirm, that you are running the same/newest version?

**Comment by icygame** [comment]
Yes, latest versions as above, on RPI  OS 12.3

**Comment by irvelervel** [comment]
Same versions as yours, I don't have a PowerStream but a Delta 2 and a Delta Mini batteries. Running HA Core on a Synology 918+.

**Comment by Nid01** [comment]
@icygame @irvelervel 
Then I currently have no clue why this is happening to you, sorry.

**Comment by Smarties202420** [comment]
@Nid01 Hi Nid, yes. Same version numbers on my end.

**Comment by Smarties202420** [comment]
@Nid01 @ all:

I figured out my issue.
I generate a new failure log and this time it was full of errors.
What finally resolved my issue:

I had to open up Port 8883 on my router.
The log entry that helped me to identify the solution:

2024-05-14 20:27:21.604 INFO (MainThread) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Connecting to MQTT Broker mqtt-e.ecoflow.com:8883

@Nid01 @ all:
Thank you for your time and support.

KR

**Comment by Smarties202420** [comment]
> @Nid01 @ all:
> 
> I figured out my issue. I generate a new failure log and this time it was full of errors. What finally resolved my issue:
> 
> I had to open up Port 8883 on my router. The log entry that helped me to identify the solution:
> 
> 2024-05-14 20:27:21.604 INFO (MainThread) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Connecting to MQTT Broker mqtt-e.ecoflow.com:8883
> 
> @Nid01 @ all: Thank you for your time and support.
> 
> KR

Mhhh, maybe I have to add some caution. As it is late now my PS turned off, but instead of zeros and dashes I see some values in the dashboard:

![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/169577794/44e7e051-bbd7-41b6-86e8-42dd892cc93b)


Will check back tomorrow and inform if those values are real and updated or not.

Have a great evening/rest of the day

**Comment by icygame** [comment]
I enabled debug logging and see these messages…
```
Detected that custom integration 'ecoflow_cloud' calls async_write_ha_state from a thread at custom_components/ecoflow_cloud/entities/__init__.py, line 85: self.async_write_ha_state(), please report it to the author of the 'ecoflow_cloud' custom integration
Detected that custom integration 'ecoflow_cloud' calls async_write_ha_state from a thread at custom_components/ecoflow_cloud/sensor.py, line 352: self.async_write_ha_state(), please report it to the author of the 'ecoflow_cloud' custom integration
Detected that custom integration 'ecoflow_cloud' calls async_write_ha_state from a thread at custom_components/ecoflow_cloud/sensor.py, line 328: self.async_write_ha_state(), please report it to the author of the 'ecoflow_cloud' custom integration `
```

**Comment by Nid01** [comment]
@icygame In your case you don't seem to be running v0.13.2 of the integration since @tolwi fixed that issue in the newest version.
https://github.com/tolwi/hassio-ecoflow-cloud/commit/b7dcf403bddc8257a6a6d9015e7d173e716071d1

**Comment by icygame** [comment]
well that's interesting because (double-checked) and it definitely reports I am running 0.13.2

is there an issue with versioning?


here is the relevant part of the diagnostics:

```
    "ecoflow_cloud": {
      "documentation": "https://github.com/tolwi/hassio-ecoflow-cloud",
      "version": "0.13.2",
      "requirements": [
        "paho-mqtt==1.6.1",
        "reactivex==4.0.4",
        "protobuf>=4.23.0"
```

**Comment by Nid01** [comment]
@icygame
Ah, I see. the commit https://github.com/tolwi/hassio-ecoflow-cloud/commit/b7dcf403bddc8257a6a6d9015e7d173e716071d1 isn't part of a release yet, and I didn't notice that, because I'm working with a fork so I don't have to wait for a new version.
You have to manually edit your local files. In the folder custom_components/ecoflow_cloud please look for `async_write_ha_state()` and replace it with `schedule_update_ha_state()`.
The commit guides you to what needs to be changed.

**Comment by icygame** [comment]
@Nid01
yep, that was it. all working now.

**Comment by irvelervel** [comment]
That fixed it also for me! Thanks!

**Comment by MrScotch72** [comment]
It works for me now too.
However, my mistake was different.
I found the solution here.
I modified my ecoflow-integration wit the Addon „File Editor“: replaced the instances of self.async_write_ha_state() With self.schedule_update_ha_state()
https://github.com/tolwi/hassio-ecoflow-cloud/issues/232?fbclid=IwZXh0bgNhZW0CMTEAAR0p74ZNPxl_MGZGCojR7RPE_TVSpYqPZ4oU84P50rlxnJa0lEpzhop4I8k_aem_AZ4smK_eZ2uVqGjUWIhB8juCwHLLLaUNLv7AkbwGmYQ6cKFoQXCBmW_m7ZhMaiorkYhEuK1mt7McOgDHMwCYf0q5#issuecomment-2089790213

**Comment by moovikafrance** [comment]
Still the same problem, no data is displayed in Home Assistant. Have you changed anything in the last few days?

**Comment by Teuroscout** [comment]
Hi,
I added two Delta 2 to the Integration. One geht's the Data and one dosn't. The Delta's both run the same Firmware (V1.0.1.134). I am sorry, I don't even know, where the Ecoflow-Cloud Integration Error Log is locatet in the Filesystem.

**Comment by Teuroscout** [comment]
I checked the Serial Number. It wasn't correct. Thanks for the hint. Now everthing works fine.
