### ISSUE TITLE
Delta 2 Max

### ISSUE THREAD

**Issue by Milchbeck** [tolwi/hassio-ecoflow-cloud#252]
After new Hass update I see no correct sensor.delta2max_discharge_remaining_time the time format is not 00:00:00

**Comment by Milchbeck** [comment]
I have self fixed with sensors [sensor:
  - platform: template
    sensors:
      delta2max_discharge_remaining_time_formatted:
        friendly_name: "Delta2Max Discharge Remaining Time"
        value_template: >
          {% set total_minutes = states('sensor.delta2max_discharge_remaining_time') | int %}
          {% set hours = (total_minutes // 60) %}
          {% set minutes = (total_minutes % 60) %}
          {{ '%02d:%02d' | format(hours, minutes) }}

      delta2max_charge_remaining_time_formatted:
        friendly_name: "Delta2Max Charge Remaining Time"
        value_template: >
          {% set total_minutes = states('sensor.delta2max_charge_remaining_time') | int %}
          {% set hours = (total_minutes // 60) %}
          {% set minutes = (total_minutes % 60) %}
          {{ '%02d:%02d' | format(hours, minutes) }}

      river2pro_charge_remaining_time_formatted:
        friendly_name: "River2Pro Charge Remaining Time"
        value_template: >
          {% set total_minutes = states('sensor.river2pro_charge_remaining_time') | int %}
          {% set hours = (total_minutes // 60) %}
          {% set minutes = (total_minutes % 60) %}
          {{ '%02d:%02d' | format(hours, minutes) }}]()

**Comment by Nid01** [comment]
Can you please use this, so your code is easier to read?
\```yaml
code
\```

And can you also provide more details on how the time is currently displayed?
A screenshot for example?
