### ISSUE TITLE
Latest firmware (V3.1.3.10) breaks integration

### ISSUE THREAD

**Issue by cfelicio** [tolwi/hassio-ecoflow-cloud#280]
Hi There,

I have 2 units of the RIver 2 connected to HA via the integration. I updated one of the units recently to the latest firmware, and now I'm still able to control the unit (e.g. shut down AC power), but no values are read from the unit, everything shows 0. I tried to unbind / rebind via the app, as well as remove / re-add to the integration, but no luck. See diagnostics below, seems like the MQTT topics are not working:

      {
        "code": "0",
        "data": {
          "sn": "...",
          "productType": 70,
          "model": 1,
          "online": 1,
          "quotaMap": {
            "mppt.faultCode": 4096,
            "mppt.dc24vState": 0,
            "pd.wattsInSum": 107,
            "bms_emsStatus.maxChargeSoc": 80,
            "pd.wifiVer": 0,
            "inv.cfgAcWorkMode": 0,
            "bms_bmsStatus.designCap": 20000,
            "bms_bmsStatus.temp": 30,
            "bms_bmsStatus.f32ShowSoc": 79.87,
            "pd.bpPowerSoc": 80,
            "pd.beepMode": 0,
            "bms_bmsStatus.outputWatts": 0,
            "pd.typec2Watts": 0,
            "inv.outputWatts": 92,
            "bms_bmsStatus.vol": 13,
            "inv.invOutFreq": 60,
            "mppt.inAmp": 0,
            "bms_emsStatus.bmsIsConnt": [
              0,
              0,
              0
            ],
            "bms_emsStatus.dsgCmd": 1,
            "mppt.inVol": 1162,
            "bms_bmsStatus.fullCap": 17998,
            "bms_emsStatus.chgVol": 13,
            "pd.icoBytes": [
              0,
              0,
              136,
              0,
              128,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0
            ],
            "inv.fanState": 0,
            "pd.usb1Watts": 0,
            "inv.cfgAcXboost": 0,
            "inv.outTemp": 59,
            "mppt.cfgAcEnabled": 1,
            "pd.bmsInfoFull": 300000,
            "mppt.res": [
              0,
              0,
              0,
              0,
              0
            ],
            "mppt.dcdc12vAmp": 0,
            "inv.invOutVol": 118033,
            "pd.extRj45Port": 0,
            "mppt.cfgAcOutVol": 120,
            "bms_emsStatus.chgAmp": 0,
            "bms_bmsStatus.errCode": 0,
            "inv.inputWatts": 107,
            "bms_emsStatus.chgState": 0,
            "bms_bmsStatus.inputWatts": 0,
            "pd.watchIsConfig": 0,
            "bms_emsStatus.openBmsIdx": 0,
            "pd.typec2Temp": 0,
            "pd.carUsedTime": 3023,
            "pd.typec1Watts": 0,
            "pd.chgDsgState": 0,
            "inv.chgPauseFlag": 0,
            "inv.acInFreq": 60,
            "mppt.carStandbyMin": 0,
            "pd.soc": 80,
            "pd.minAcoutSoc": 255,
            "inv.invOutAmp": 930,
            "mppt.cfgAcOutFreq": 60,
            "bms_emsStatus.fanLevel": 0,
            "mppt.carOutVol": 0,
            "inv.dcInVol": 0,
            "mppt.cfgAcXboost": 1,
            "pd.ext3p8Port": 0,
            "pd.dsgPowerDC": 17,
            "inv.SlowChgWatts": 0,
            "inv.dcInAmp": 0,
            "mppt.carOutAmp": 0,
            "pd.typecUsedTime": 1197,
            "bms_bmsStatus.remainCap": 14373,
            "pd.brightLevel": 100,
            "inv.dcInTemp": 0,
            "bms_emsStatus.maxAvailNum": 0,
            "mppt.dcdc12vVol": 0,
            "bms_emsStatus.maxCloseOilEb": 0,
            "pd.wattsOutSum": 87,
            "mppt.scrStandbyMin": 300,
            "mppt.carOutWatts": 0,
            "pd.relaySwitchCnt": 0,
            "mppt.outVol": 13273,
            "bms_emsStatus.f32LcdShowSoc": 79.93,
            "inv.cfgAcEnabled": 1,
            "bms_emsStatus.paraVolMax": 0,
            "mppt.chgType": 0,
            "bms_bmsStatus.bmsFault": 0,
            "inv.acDipSwitch": 0,
            "mppt.cfgChgType": 0,
            "bms_emsStatus.paraVolMin": 0,
            "pd.pdInfoIncre": 2000,
            "inv.standbyMins": 0,
            "inv.dischargeType": 0,
            "mppt.chgState": 0,
            "pd.carState": 0,
            "pd.acAutoOutConfig": 0,
            "pd.invUsedTime": 62247,
            "bms_emsStatus.bmsWarState": 0,
            "mppt.carState": 0,
            "mppt.dischargeType": 0,
            "pd.typec1Temp": 0,
            "pd.dcInUsedTime": 0,
            "bms_bmsStatus.sysVer": 50397534,
            "mppt.carTemp": 24,
            "pd.model": 0,
            "mppt.outWatts": 0,
            "bms_bmsStatus.minCellVol": 3313,
            "bms_bmsStatus.cycles": 1,
            "pd.bmsRunIncre": 30000,
            "pd.wifiAutoRcvy": 0,
            "pd.remainTime": 5999,
            "bms_bmsStatus.maxCellVol": 3313,
            "bms_bmsStatus.type": 1,
            "mppt.outAmp": 0,
            "bms_bmsStatus.maxCellTemp": 30,
            "pd.ext4p8Port": 0,
            "bms_bmsStatus.cellId": 2,
            "mppt.chgPauseFlag": 0,
            "pd.typecChaWatts": 0,
            "bms_bmsStatus.minMosTemp": 30,
            "mppt.acStandbyMins": 0,
            "mppt.powStandbyMin": 0,
            "bms_emsStatus.minOpenOilEb": 0,
            "pd.hysteresisAdd": 5,
            "inv.chargerType": 1,
            "pd.chgSunPower": 0,
            "pd.carTemp": 0,
            "bms_bmsStatus.bqSysStatReg": 0,
            "inv.acInAmp": 0,
            "bms_emsStatus.chgRemainTime": 5999,
            "pd.dsgPowerAC": 148,
            "bms_bmsStatus.openBmsIdx": 1,
            "pd.qcUsb2Watts": 0,
            "pd.wireWatts": 0,
            "bms_bmsStatus.num": 0,
            "pd.chgPowerAC": 390,
            "pd.lcdOffSec": 300,
            "pd.acAutoOutPause": 255,
            "mppt.beepState": 0,
            "bms_bmsStatus.soc": 80,
            "inv.acInVol": 118556,
            "inv.FastChgWatts": 0,
            "pd.sysVer": 33621322,
            "pd.pdInfoFull": 300000,
            "mppt.dc24vTemp": 0,
            "bms_emsStatus.chgCmd": 1,
            "bms_bmsStatus.tagChgAmp": 0,
            "pd.bmsInfoIncre": 15000,
            "bms_bmsStatus.maxMosTemp": 30,
            "mppt.cfgChgWatts": 100,
            "pd.qcUsb1Watts": 0,
            "bms_bmsStatus.minCellTemp": 30,
            "pd.chgPowerDC": 0,
            "mppt.swVer": 50397534,
            "pd.standbyMin": 30,
            "mppt.x60ChgType": 0,
            "inv.cfgAcOutFreq": 2,
            "bms_bmsStatus.soh": 100,
            "inv.errCode": 0,
            "bms_emsStatus.openUpsFlag": 1,
            "mppt.dcdc12vWatts": 0,
            "bms_emsStatus.minDsgSoc": 20,
            "pd.usbqcUsedTime": 0,
            "pd.dcOutState": 0,
            "bms_bmsStatus.remainTime": 0,
            "mppt.inWatts": 0,
            "bms_emsStatus.emsIsNormalFlag": 1,
            "pd.usbUsedTime": 0,
            "pd.mpptUsedTime": 0,
            "inv.reserved": [
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0
            ],
            "mppt.mpptTemp": 0,
            "pd.wifiRssi": 0,
            "pd.pdRunIncre": 30000,
            "bms_bmsStatus.amp": 0,
            "inv.invType": 0,
            "bms_emsStatus.lcdShowSoc": 80,
            "inv.cfgAcOutVol": 0,
            "bms_emsStatus.bmsModel": 0,
            "pd.errCode": 0,
            "pd.carWatts": 0,
            "pd.usb2Watts": 0,
            "mppt.dcChgCurrent": 8000,
            "bms_emsStatus.dsgRemainTime": 5999,
            "inv.sysVer": 67174714
          }
        },
        "id": 999997615,
        "moduleType": 0,
        "operateType": "latestQuotas",
        "version": "1.1"
      }
    ],
    "raw_data": []
  }
}

For comparison, this is what comes up in the working unit with the older firmware (3.1.3.06)

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.8.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Vancouver",
    "os_name": "Linux",
    "os_version": "6.6.33-haos",
    "supervisor": "2024.08.0",
    "host_os": "Home Assistant OS 12.4",
    "docker_version": "26.1.4",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.6.3",
      "requirements": [
        "prettytable==3.10.0"
      ]
    },
    "tapo_control": {
      "documentation": "https://github.com/JurajNyiri/HomeAssistant-Tapo-Control",
      "version": "5.6.0",
      "requirements": [
        "pytapo==3.3.30"
      ]
    },
    "winix": {
      "documentation": "https://github.com/iprak/winix",
      "version": "1.1.7",
      "requirements": [
        "winix==0.2.1"
      ]
    },
    "local_luftdaten": {
      "documentation": "https://github.com/lichtteil/local_luftdaten/",
      "version": "2.2.0",
      "requirements": []
    },
    "home_connect_alt": {
      "documentation": "https://github.com/ekutner/home-connect-hass",
      "version": "1.1.7",
      "requirements": [
        "home-connect-async==0.8.0"
      ]
    },
    "smartthinq_sensors": {
      "documentation": "https://github.com/ollo69/ha-smartthinq-sensors",
      "version": "0.39.2",
      "requirements": [
        "pycountry>=23.12.11",
        "xmltodict>=0.13.0",
        "charset_normalizer>=3.2.0"
      ]
    },
    "ecoflow_cloud": {
      "documentation": "https://github.com/tolwi/hassio-ecoflow-cloud",
      "version": "0.13.4",
      "requirements": [
        "paho-mqtt==1.6.1",
        "reactivex==4.0.4",
        "protobuf>=4.23.0"
      ]
    },
    "wyzeapi": {
      "documentation": "https://github.com/SecKatie/ha-wyzeapi#readme",
      "version": "0.1.27",
      "requirements": [
        "wyzeapy>=0.5.23,<0.5.24"
      ]
    },
    "generic_hygrostat": {
      "documentation": "https://github.com/basschipper/homeassistant-generic-hygrostat",
      "version": "0.8.0",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "powercalc": {
      "documentation": "https://github.com/bramstroker/homeassistant-powercalc",
      "version": "v1.14.0",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "moonraker": {
      "documentation": "https://moonraker-home-assistant.readthedocs.io/en/latest/",
      "version": "1.2.3",
      "requirements": [
        "moonraker-api==2.0.5"
      ]
    },
    "rd200_ble": {
      "documentation": "https://www.github.com/jdeath/rd200v2",
      "version": "1.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "ecoflow_cloud",
    "name": "Ecoflow-Cloud",
    "codeowners": [
      "tolwi"
    ],
    "config_flow": true,
    "documentation": "https://github.com/tolwi/hassio-ecoflow-cloud",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/tolwi/hassio-ecoflow-cloud/issues",
    "requirements": [
      "paho-mqtt==1.6.1",
      "reactivex==4.0.4",
      "protobuf>=4.23.0"
    ],
    "version": "0.13.4",
    "is_built_in": false
  },
  "setup_times": {},
  "data": {
    "device": "RIVER_2",
    "params": {
      "bms_bmsStatus.amp": 0,
      "bms_bmsStatus.bmsFault": 0,
      "bms_bmsStatus.bqSysStatReg": 0,
      "bms_bmsStatus.cellId": 2,
      "bms_bmsStatus.cycles": 3,
      "bms_bmsStatus.designCap": 20000,
      "bms_bmsStatus.errCode": 0,
      "bms_bmsStatus.f32ShowSoc": 78.8,
      "bms_bmsStatus.fullCap": 17994,
      "bms_bmsStatus.inputWatts": 0,
      "bms_bmsStatus.maxCellTemp": 27,
      "bms_bmsStatus.maxCellVol": 3291,
      "bms_bmsStatus.maxMosTemp": 27,
      "bms_bmsStatus.minCellTemp": 27,
      "bms_bmsStatus.minCellVol": 3291,
      "bms_bmsStatus.minMosTemp": 27,
      "bms_bmsStatus.num": 0,
      "bms_bmsStatus.openBmsIdx": 1,
      "bms_bmsStatus.outputWatts": 0,
      "bms_bmsStatus.remainCap": 14182,
      "bms_bmsStatus.remainTime": 0,
      "bms_bmsStatus.soc": 79,
      "bms_bmsStatus.soh": 100,
      "bms_bmsStatus.sysVer": 50397534,
      "bms_bmsStatus.tagChgAmp": 20000,
      "bms_bmsStatus.temp": 27,
      "bms_bmsStatus.type": 1,
      "bms_bmsStatus.vol": 13,
      "bms_emsStatus.bmsIsConnt": [
        0,
        0,
        0
      ],
      "bms_emsStatus.bmsModel": 0,
      "bms_emsStatus.bmsWarState": 0,
      "bms_emsStatus.chgAmp": 0,
      "bms_emsStatus.chgCmd": 2,
      "bms_emsStatus.chgRemainTime": 5999,
      "bms_emsStatus.chgState": 0,
      "bms_emsStatus.chgVol": 13,
      "bms_emsStatus.dsgCmd": 1,
      "bms_emsStatus.dsgRemainTime": 5999,
      "bms_emsStatus.emsIsNormalFlag": 1,
      "bms_emsStatus.f32LcdShowSoc": 78.9,
      "bms_emsStatus.fanLevel": 0,
      "bms_emsStatus.lcdShowSoc": 79,
      "bms_emsStatus.maxAvailNum": 0,
      "bms_emsStatus.maxChargeSoc": 80,
      "bms_emsStatus.maxCloseOilEb": 0,
      "bms_emsStatus.minDsgSoc": 20,
      "bms_emsStatus.minOpenOilEb": 0,
      "bms_emsStatus.openBmsIdx": 0,
      "bms_emsStatus.openUpsFlag": 1,
      "bms_emsStatus.paraVolMax": 0,
      "bms_emsStatus.paraVolMin": 0,
      "inv.FastChgWatts": 0,
      "inv.SlowChgWatts": 0,
      "inv.acDipSwitch": 0,
      "inv.acInAmp": 974,
      "inv.acInFreq": 60,
      "inv.acInVol": 120717,
      "inv.cfgAcEnabled": 1,
      "inv.cfgAcOutFreq": 2,
      "inv.cfgAcOutVol": 0,
      "inv.cfgAcWorkMode": 0,
      "inv.cfgAcXboost": 0,
      "inv.chargerType": 1,
      "inv.chgPauseFlag": 0,
      "inv.dcInAmp": 0,
      "inv.dcInTemp": 0,
      "inv.dcInVol": 0,
      "inv.dischargeType": 0,
      "inv.errCode": 0,
      "inv.fanState": 0,
      "inv.inputWatts": 216,
      "inv.invOutAmp": 2036,
      "inv.invOutFreq": 60,
      "inv.invOutVol": 120177,
      "inv.invType": 0,
      "inv.outTemp": 39,
      "inv.outputWatts": 216,
      "inv.reserved": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "inv.standbyMins": 0,
      "inv.sysVer": 67174714,
      "mppt.acStandbyMins": 0,
      "mppt.beepState": 0,
      "mppt.carOutAmp": 0,
      "mppt.carOutVol": 0,
      "mppt.carOutWatts": 0,
      "mppt.carStandbyMin": 0,
      "mppt.carState": 0,
      "mppt.carTemp": 24,
      "mppt.cfgAcEnabled": 1,
      "mppt.cfgAcOutFreq": 60,
      "mppt.cfgAcOutVol": 120,
      "mppt.cfgAcXboost": 1,
      "mppt.cfgChgType": 0,
      "mppt.cfgChgWatts": 100,
      "mppt.chgPauseFlag": 0,
      "mppt.chgState": 0,
      "mppt.chgType": 0,
      "mppt.dc24vState": 0,
      "mppt.dc24vTemp": 0,
      "mppt.dcChgCurrent": 8000,
      "mppt.dcdc12vAmp": 0,
      "mppt.dcdc12vVol": 0,
      "mppt.dcdc12vWatts": 0,
      "mppt.dischargeType": 0,
      "mppt.faultCode": 4096,
      "mppt.inAmp": 3,
      "mppt.inVol": 1135,
      "mppt.inWatts": 0,
      "mppt.mpptTemp": 0,
      "mppt.outAmp": 0,
      "mppt.outVol": 13218,
      "mppt.outWatts": 0,
      "mppt.powStandbyMin": 0,
      "mppt.res": [
        0,
        0,
        0,
        0,
        0
      ],
      "mppt.scrStandbyMin": 300,
      "mppt.swVer": 50397534,
      "mppt.x60ChgType": 0,
      "pd.acAutoOutConfig": 0,
      "pd.acAutoOutPause": 255,
      "pd.beepMode": 0,
      "pd.bpPowerSoc": 80,
      "pd.brightLevel": 100,
      "pd.carState": 0,
      "pd.carTemp": 0,
      "pd.carUsedTime": 2884,
      "pd.carWatts": 0,
      "pd.chgDsgState": 0,
      "pd.chgPowerAC": 16841,
      "pd.chgPowerDC": 0,
      "pd.chgSunPower": 0,
      "pd.dcInUsedTime": 0,
      "pd.dcOutState": 0,
      "pd.dsgPowerAC": 16102,
      "pd.dsgPowerDC": 17,
      "pd.errCode": 0,
      "pd.ext3p8Port": 0,
      "pd.ext4p8Port": 0,
      "pd.extRj45Port": 0,
      "pd.hysteresisAdd": 5,
      "pd.icoBytes": [
        0,
        0,
        136,
        0,
        128,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "pd.invUsedTime": 550009,
      "pd.lcdOffSec": 300,
      "pd.minAcoutSoc": 255,
      "pd.model": 0,
      "pd.mpptUsedTime": 0,
      "pd.qcUsb1Watts": 0,
      "pd.qcUsb2Watts": 0,
      "pd.relaySwitchCnt": 0,
      "pd.remainTime": 5999,
      "pd.soc": 79,
      "pd.standbyMin": 30,
      "pd.sysVer": 33621313,
      "pd.typec1Temp": 0,
      "pd.typec1Watts": 0,
      "pd.typec2Temp": 0,
      "pd.typec2Watts": 0,
      "pd.typecChaWatts": 0,
      "pd.typecUsedTime": 1209,
      "pd.usb1Watts": 0,
      "pd.usb2Watts": 0,
      "pd.usbUsedTime": 0,
      "pd.usbqcUsedTime": 0,
      "pd.watchIsConfig": 0,
      "pd.wattsInSum": 216,
      "pd.wattsOutSum": 216,
      "pd.wifiAutoRcvy": 0,
      "pd.wifiRssi": 0,
      "pd.wifiVer": 0,
      "pd.wireWatts": 0,
      "timestamp": 1723351978
    },
    "set": [],
    "set_reply": [],
    "get": [
      {
        "from": "HomeAssistant",
        "id": "...",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      }
    ],
    "get_reply": [
      {
        "code": "0",
        "data": {
          "sn": "...",
          "productType": 70,
          "model": 1,
          "online": 1,
          "quotaMap": {
            "mppt.faultCode": 4096,
            "mppt.dc24vState": 0,
            "pd.wattsInSum": 227,
            "bms_emsStatus.maxChargeSoc": 80,
            "pd.wifiVer": 0,
            "inv.cfgAcWorkMode": 0,
            "bms_bmsStatus.designCap": 20000,
            "bms_bmsStatus.temp": 27,
            "bms_bmsStatus.f32ShowSoc": 78.8,
            "pd.bpPowerSoc": 80,
            "pd.beepMode": 0,
            "bms_bmsStatus.outputWatts": 0,
            "pd.typec2Watts": 0,
            "inv.outputWatts": 227,
            "bms_bmsStatus.vol": 13,
            "inv.invOutFreq": 60,
            "mppt.inAmp": 3,
            "bms_emsStatus.bmsIsConnt": [
              0,
              0,
              0
            ],
            "bms_emsStatus.dsgCmd": 1,
            "mppt.inVol": 1135,
            "bms_bmsStatus.fullCap": 17994,
            "bms_emsStatus.chgVol": 13,
            "pd.icoBytes": [
              0,
              0,
              136,
              0,
              128,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0
            ],
            "inv.fanState": 0,
            "pd.usb1Watts": 0,
            "inv.cfgAcXboost": 0,
            "inv.outTemp": 39,
            "mppt.cfgAcEnabled": 1,
            "pd.bmsInfoFull": 300000,
            "mppt.res": [
              0,
              0,
              0,
              0,
              0
            ],
            "mppt.dcdc12vAmp": 0,
            "inv.invOutVol": 119811,
            "pd.extRj45Port": 0,
            "mppt.cfgAcOutVol": 120,
            "bms_emsStatus.chgAmp": 0,
            "bms_bmsStatus.errCode": 0,
            "inv.inputWatts": 227,
            "bms_emsStatus.chgState": 0,
            "bms_bmsStatus.inputWatts": 0,
            "pd.watchIsConfig": 0,
            "bms_emsStatus.openBmsIdx": 0,
            "pd.typec2Temp": 0,
            "pd.carUsedTime": 2884,
            "pd.typec1Watts": 0,
            "pd.chgDsgState": 0,
            "inv.chgPauseFlag": 0,
            "inv.acInFreq": 60,
            "mppt.carStandbyMin": 0,
            "pd.soc": 79,
            "pd.minAcoutSoc": 255,
            "inv.invOutAmp": 2036,
            "mppt.cfgAcOutFreq": 60,
            "bms_emsStatus.fanLevel": 0,
            "mppt.carOutVol": 0,
            "inv.dcInVol": 0,
            "mppt.cfgAcXboost": 1,
            "pd.ext3p8Port": 0,
            "pd.dsgPowerDC": 17,
            "inv.SlowChgWatts": 0,
            "inv.dcInAmp": 0,
            "mppt.carOutAmp": 0,
            "pd.typecUsedTime": 1209,
            "bms_bmsStatus.remainCap": 14183,
            "pd.brightLevel": 100,
            "inv.dcInTemp": 0,
            "bms_emsStatus.maxAvailNum": 0,
            "mppt.dcdc12vVol": 0,
            "bms_emsStatus.maxCloseOilEb": 0,
            "pd.wattsOutSum": 227,
            "mppt.scrStandbyMin": 300,
            "mppt.carOutWatts": 0,
            "pd.relaySwitchCnt": 0,
            "mppt.outVol": 13218,
            "bms_emsStatus.f32LcdShowSoc": 78.9,
            "inv.cfgAcEnabled": 1,
            "bms_emsStatus.paraVolMax": 0,
            "mppt.chgType": 0,
            "bms_bmsStatus.bmsFault": 0,
            "inv.acDipSwitch": 0,
            "mppt.cfgChgType": 0,
            "bms_emsStatus.paraVolMin": 0,
            "pd.pdInfoIncre": 2000,
            "inv.standbyMins": 0,
            "inv.dischargeType": 0,
            "mppt.chgState": 0,
            "pd.carState": 0,
            "pd.acAutoOutConfig": 0,
            "pd.invUsedTime": 550009,
            "bms_emsStatus.bmsWarState": 0,
            "mppt.carState": 0,
            "mppt.dischargeType": 0,
            "pd.typec1Temp": 0,
            "pd.dcInUsedTime": 0,
            "bms_bmsStatus.sysVer": 50397534,
            "mppt.carTemp": 24,
            "pd.model": 0,
            "mppt.outWatts": 0,
            "bms_bmsStatus.minCellVol": 3291,
            "bms_bmsStatus.cycles": 3,
            "pd.bmsRunIncre": 30000,
            "pd.wifiAutoRcvy": 0,
            "pd.remainTime": 5999,
            "bms_bmsStatus.maxCellVol": 3291,
            "bms_bmsStatus.type": 1,
            "mppt.outAmp": 0,
            "bms_bmsStatus.maxCellTemp": 27,
            "pd.ext4p8Port": 0,
            "bms_bmsStatus.cellId": 2,
            "mppt.chgPauseFlag": 0,
            "pd.typecChaWatts": 0,
            "bms_bmsStatus.minMosTemp": 27,
            "mppt.acStandbyMins": 0,
            "mppt.powStandbyMin": 0,
            "bms_emsStatus.minOpenOilEb": 0,
            "pd.hysteresisAdd": 5,
            "inv.chargerType": 1,
            "pd.chgSunPower": 0,
            "pd.carTemp": 0,
            "bms_bmsStatus.bqSysStatReg": 0,
            "inv.acInAmp": 974,
            "bms_emsStatus.chgRemainTime": 5999,
            "pd.dsgPowerAC": 16102,
            "bms_bmsStatus.openBmsIdx": 1,
            "pd.qcUsb2Watts": 0,
            "pd.wireWatts": 0,
            "bms_bmsStatus.num": 0,
            "pd.chgPowerAC": 16841,
            "pd.lcdOffSec": 300,
            "pd.acAutoOutPause": 255,
            "mppt.beepState": 0,
            "bms_bmsStatus.soc": 79,
            "inv.acInVol": 120355,
            "inv.FastChgWatts": 0,
            "pd.sysVer": 33621313,
            "pd.pdInfoFull": 300000,
            "mppt.dc24vTemp": 0,
            "bms_emsStatus.chgCmd": 2,
            "bms_bmsStatus.tagChgAmp": 20000,
            "pd.bmsInfoIncre": 15000,
            "bms_bmsStatus.maxMosTemp": 27,
            "mppt.cfgChgWatts": 100,
            "pd.qcUsb1Watts": 0,
            "bms_bmsStatus.minCellTemp": 27,
            "pd.chgPowerDC": 0,
            "mppt.swVer": 50397534,
            "pd.standbyMin": 30,
            "mppt.x60ChgType": 0,
            "inv.cfgAcOutFreq": 2,
            "bms_bmsStatus.soh": 100,
            "inv.errCode": 0,
            "bms_emsStatus.openUpsFlag": 1,
            "mppt.dcdc12vWatts": 0,
            "bms_emsStatus.minDsgSoc": 20,
            "pd.usbqcUsedTime": 0,
            "pd.dcOutState": 0,
            "bms_bmsStatus.remainTime": 0,
            "mppt.inWatts": 0,
            "bms_emsStatus.emsIsNormalFlag": 1,
            "pd.usbUsedTime": 0,
            "pd.mpptUsedTime": 0,
            "inv.reserved": [
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0
            ],
            "mppt.mpptTemp": 0,
            "pd.wifiRssi": 0,
            "pd.pdRunIncre": 30000,
            "bms_bmsStatus.amp": 0,
            "inv.invType": 0,
            "bms_emsStatus.lcdShowSoc": 79,
            "inv.cfgAcOutVol": 0,
            "bms_emsStatus.bmsModel": 0,
            "pd.errCode": 0,
            "pd.carWatts": 0,
            "pd.usb2Watts": 0,
            "mppt.dcChgCurrent": 8000,
            "bms_emsStatus.dsgRemainTime": 5999,
            "inv.sysVer": 67174714
          }
        },
        "id": 999997602,
        "moduleType": 0,
        "operateType": "latestQuotas",
        "version": "1.1"
      }
    ],
    "raw_data": []
  }
}

**Comment by Nid01** [comment]
More people are having the same issue: https://github.com/tolwi/hassio-ecoflow-cloud/issues/283
Can you recall, when you last updated your app so we can better understand if it is a firmware, app or API related problem?

**Comment by cfelicio** [comment]
Ah, I missed the other one. The issues are not exactly the same (I never get any data on the 2nd device, even with the app open), but I'll close this one for now, I think they are related.
