### ISSUE TITLE
Smart Plug (public API integration; Version v1.0.0-pre4), Watt-Reading wrong by Factor 10?

### ISSUE THREAD

**Issue by andreasbuff** [tolwi/hassio-ecoflow-cloud#286]
Hello 

Thank you for working on the new Release for public API Integrations! **Great work.** 

- In my Pre4-Release I think, that the Watt-Reading I am getting is wrong by a factor of 10?

e.g.
Ecoflow-App showing        1 Watt
HA-Integration showing: 10 Watt

or 
Ecofow-App showing:      17 Watt
HA-Integration showing: 170 Watt

Feature Request:
- If it where possible, to chose update-intervall (e.g. faster refresh-cycles), this would also be great. 
-
Thank you!!

Core: 2024.8.2
HA:    13.1.rc1
Supervisor: 2024.08.0

Ecoflow-Cloud:  v1.0.0-pre4)

**Comment by incrediblehorst** [comment]
I have got the same issue
