### ISSUE TITLE
 (('accessKey is invalid',), {}) Beta Pre4

### ISSUE THREAD

**Issue by NathanWarrick** [tolwi/hassio-ecoflow-cloud#287]
When entering my public API and private key I receive an error "(('accessKey is invalid',), {})" and no device is added to home assistant. 
Running HA 2024.8.1
![image](https://github.com/user-attachments/assets/97d3eaae-51e8-4119-b730-fe691857d25f)

**Comment by tolwi** [comment]
it's an ecoflow api server response

**Comment by tensor5g** [comment]
I am getting the same issue.  I have verified my access and secret key are valid by doing a test API call

```
curl -X GET "https://api-a.ecoflow.com/iot-open/sign/device/list" \
-H "accessKey:$ACCESS_KEY" \
-H "timestamp:$TIMESTAMP" \
-H "nonce:$NONCE" \
-H "sign:$SIGN"
```

which returns
```
{"code":"0","message":"Success","data":[{"sn":"***","deviceName":"RIVER 2-1003","online":1,"productName":"RIVER 2"}],"eagleEyeTraceId":"***","tid":""}
```

Does the "Device group" name matter? I've tried setting it to match the device name, but that didn't help.

Are there any other endpoints you want me to test? Is there a way I can get you debug logs?

Thanks
