### ISSUE TITLE
Can't get devices

### ISSUE THREAD

**Issue by incrediblehorst** [tolwi/hassio-ecoflow-cloud#292]
I've manually installed the v1.0.0-pre4 and use HA 2024.8.2. I followed the wizzard and entered my access and secret key which I got from developer.ecoflow.com. When submitting the form I get the following exception:

```
Unexpected exception in fetch device action
Traceback (most recent call last):
  File "/config/custom_components/ecoflow_cloud/config_flow.py", line 134, in async_step_api
    devices = await auth.fetch_all_available_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/api/public_api.py", line 43, in fetch_all_available_devices
    result.append(self.__create_device_info(device["sn"], device["deviceName"], device["productName"]))
                                                          ~~~~~~^^^^^^^^^^^^^^
KeyError: 'deviceName'
```
I've restarted HA several times - without any success

**Comment by Nid01** [comment]
@incrediblehorst Could it be, that not every device in your app has a custom name set?
In that case you that element is missing in the response.

**Comment by incrediblehorst** [comment]
Ah now it works. Nice - thank you =)
