### ISSUE TITLE
Unexpected MQTT disconnection

### ISSUE THREAD

**Issue by incrediblehorst** [tolwi/hassio-ecoflow-cloud#293]
Versions:
HA Version 2024.8.2. I
main repo 23.08.2024

After round about 1 minute the data is stuck and I'll get the error: 
`Unexpected MQTT disconnection: 7 (Error count 1). Will auto-reconnect`

I have added two sockets and one powerstream. I think the delta pro isn't implemented yet-

**Comment by niltrip** [comment]
I also have the problem when I try to include a PowerOcean via Public API.

**Comment by jmgfr** [comment]
Hi, 
This happend if more than one client is connected to the server with the same client id.
to avoid this, reconfigure the integration and chose a unique value when asked to inform your "installation site"
Ex : Home-XXXXXXXXXXXXXXXX where XXXXXXXXX is really unique in the world
I don't have any disconnection thince I have make this
The "Installation site" is used as client ID

**Comment by incrediblehorst** [comment]
@jmgfr nice, that does the trick. <3
