### ISSUE TITLE
What am I doing wrong?  HA / repository invalid

### ISSUE THREAD

**Issue by rokpew** [tolwi/hassio-ecoflow-cloud#303]
All, just installed HA and tried to add this as an add on repository, but it's showing invalid.

![image](https://github.com/user-attachments/assets/d0d9f237-93af-4d2e-9d9b-a2a1a14f5fcf)

**Comment by Superkikim** [comment]
Try removing .git 

Use only 

https://github.com/tolwi/hassio-ecoflow-cloud

**Comment by rokpew** [comment]
![image](https://github.com/user-attachments/assets/73ad8e99-1599-4bce-bad7-287e61e6d539)

**Comment by Superkikim** [comment]
What are your versions of HomeAssistant and HACS ?

I have 2024.8.3 and 2.0.0

Just realize one can just put tolwi/hassio-ecoflow-cloud but I think URL should work as well. I was able to add it to both my test instance and my prod instance.

**Comment by rokpew** [comment]
![image](https://github.com/user-attachments/assets/c311538b-3858-4d7c-bb73-21069892dd10)

**Comment by rokpew** [comment]
I got it working... in short, HACS wasn't properly working and I had to get that fixed first.

**Comment by Superkikim** [comment]
> I got it working... in short, HACS wasn't properly working and I had to get that fixed first.
> 
> 

Interesting. Good to know. 👍🏼

**Comment by dannyharzbecker** [comment]
How did you fix the HACS?  i have the same Issue.
