### ISSUE TITLE
Wrong spelling of Powerstream Sensor 'solar_1_current'

### ISSUE THREAD

**Issue by xt-tom** [tolwi/hassio-ecoflow-cloud#305]
v1.1.0-pre6: Wrong spelling - there is one “r” too many in Powerstream sensor 'solar_1_currrent'.

**Comment by Dev-Fabry** [comment]
Hi
On which API (Application o Open) ?

In Open Api and version 1.1.0-pre7 I have the correct "solar_1_current"

Please try to delete integration, download the latest version, recreate integration and re-check

**Comment by Dev-Fabry** [comment]
I confirm that the problem was present in older versions (perhaps 0.13.4) but is no longer present in 1.1.0

This issue can and should be closed
