### ISSUE TITLE
Data freeze with data over Developer API

### ISSUE THREAD

**Issue by Naumsede** [tolwi/hassio-ecoflow-cloud#308]
Since yesterday I have totally freezed data with the new option of integrating the devices (2 Powerstreams and 1 Delta 2 Max) over the Developer/Official API.
I just get one new data point when reloading the integration...
From time to time one of the Powerstreams (seperate account with other key and secret) gets new data.
Does anybody else have this issue?

I appreciate any help

**Comment by giovanne123** [comment]
Do you had a look to the logs, maybe error 5 related to too many client_ids and you only get once "old" data when reloading!?

Only for info/idea...

https://github.com/tolwi/hassio-ecoflow-cloud/issues/306

**Comment by Naumsede** [comment]
Per new key and secret from EcoFlow Developer API solved.
See other issue with Data Freeze from giovanne.
