### ISSUE TITLE
Failed to connect to MQTT: bad username or password

### ISSUE THREAD

**Issue by HHoppenstock** [tolwi/hassio-ecoflow-cloud#31]
Since 4:45 am the integration stopped working and throws the credentials error.
The credentials work fine in the official Ecoflow app( android and iOS).

**Comment by EvgveneSV** [comment]
Same problem, no data since 4:41 UTC

**Comment by raphaelsavina** [comment]
Looks like Ecoflow API is not working.

A call to https://api.ecoflow.com/auth/login with Postman returns:

```
{
    "code": "405",
    "message": "Method Not Allowed"
}
```

**Comment by nikowait** [comment]
exactement la même chose ...depuis ce matin sur mon river 2max

**Comment by StefanWeyh** [comment]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt
Source: custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py:232
Integration: Ecoflow-Cloud (documentation, issues)
First occurred: 13:19:49 (11 occurrences)
Last logged: 13:30:54

Failed to connect to MQTT: bad username or password

**Comment by demey** [comment]
Same problem here.
[custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Failed to connect to MQTT: bad username or password

**Comment by StefanWeyh** [comment]
sorry but where do i put that? I'm new to HomeAssistant. Excuse the bad english. come from Germany

**Comment by nikowait** [comment]
> 

oui merci met ou rajoutons ca je suis nouveau aussi sur maison assistant

**Comment by nikowait** [comment]
moi aussi la je cherche met je trouve pas

**Comment by tolwi** [comment]
try v0.8.4 (@joejeff123 thanks!)

**Comment by raphaelsavina** [comment]
Thank you @tolwi and @joejeff123 indeed v0.8.4 resolved the issue.
Raphaël

**Comment by StefanWeyh** [comment]
Thank you @tolwi and @joejeff123 
Now it works 🥳

**Comment by HHoppenstock** [comment]
> Looks like Ecoflow API is not working.
> 
> A call to https://api.ecoflow.com/auth/login with Postman returns:
> 
> ```
> {
>     "code": "405",
>     "message": "Method Not Allowed"
> }
> ```


> try v0.8.4 (@joejeff123 thanks!)
