### ISSUE TITLE
MQTT connect: The connection was refused. 

### ISSUE THREAD

**Issue by incrediblehorst** [tolwi/hassio-ecoflow-cloud#310]
For round about 1h - after I've rebooted HomeAssistant - I don't get updates. I'm using the Pre 7 version. 

In the logs I get a lot of errors: MQTT connect: The connection was refused. 

Reconfiguring the component or restarting homeassistant doesn't solve the problem

**Comment by Naumsede** [comment]
Do you use the Developer API?
Then you have to get a renewed key and secret.
They have them to be filled in with "new configuring" the device (e.g. powerstream) in the integration.
See the issue from giavonne.

**Comment by incrediblehorst** [comment]
Thanks, problem solved
