### ISSUE TITLE
I can't add API keys

### ISSUE THREAD

**Issue by msergein** [tolwi/hassio-ecoflow-cloud#314]
When adding a device, the option to add as an API (with its own keys) is not shown

Ecoflow-Cloud: 0.13.4

HA:
Core 2024.8.3
UI 20240809.0
Docker on Linux

**Comment by Dev-Fabry** [comment]
Hi, You have a pair of keys for your account

Same keys for all devices (registred to you), not a pair for every device

You specified the pair of keys only with first device and reuse it for all others

**Comment by msergein** [comment]
It worked on the pre version, but I can only add one device and there is no translation for my language (Russian), but this is not critical for me - I only need one device for automation, thanks!

**Comment by Dev-Fabry** [comment]
To add second device, please reconfigure integration, confirm keys and then select the "add device" menu that will appear

**Comment by msergein** [comment]
yes, with reconfiguration I was able to add another device, thanks

**Comment by msergein** [comment]
yes, with reconfiguration I was able to add another device, thanks
