### ISSUE TITLE
PowerStream, Application API (latest codebase), DIAGNOSTIC Type not working

### ISSUE THREAD

**Issue by Dev-Fabry** [tolwi/hassio-ecoflow-cloud#316]
Hi, I wanted to see if the ESP Temp value was also present with the Application API, so I configured the PowerStream as DIAGNOSTIC type.

But it doesn't work if I select that type I get a lot of errors and no data is read.
Only if I use POWERSTREAM type is working (but also with a error)

Some errors and warnings from the log:

> Source: custom_components/ecoflow_cloud/api/ecoflow_mqtt.py:104
> Error: Bad logger message: Message publish failed: The client is not currently connected. (('Error on topic /app/1811045495668867074/HW51******/thing/property/get and message {"from": "HomeAssistant", "id": "999928185", "version": "1.1", "moduleType": 0, "operateType": "latestQuotas", "params": {}}',)) 

> Source: custom_components/ecoflow_cloud/devices/__init__.py:141
> Warning: Exception: Expecting value: line 2 column 1 (char 1). Trying to load json.

> Source: custom_components/ecoflow_cloud/devices/__init__.py:144
> Error: constant: 'utf-8' codec can't decode byte 0x98 in position 4: invalid start byte. Ignoring message and waiting for the next one.

> Source: custom_components/ecoflow_cloud/devices/data_holder.py:85
> Error: Bad logger message: Error updating data ((TypeError("'NoneType' object is not subscriptable"),))

With Powerstream type instead (integration seems to work):

> Source: custom_components/ecoflow_cloud/devices/internal/powerstream.py:150
> Error: Error parsing message

**Comment by tolwi** [comment]
Powerstream custom integration uses protobuf data, so actually there is nothing to diagnose. 
I've removed DIAGNOSTIC device type from the custom integration device selection.
