### ISSUE TITLE
PowerStream stop updating sensors

### ISSUE THREAD

**Issue by vicivars** [tolwi/hassio-ecoflow-cloud#322]
Hello, my ecoflow powerstream integration stops updating the sensors when the app is closed and they are not updated until the mobile application is opened again. I have installed version 1.1.07-pre which I read solved this error but it remains the same. What can I do?
![image](https://github.com/user-attachments/assets/68b1323b-9deb-48d1-95b2-e5015d52fae2)

**Comment by Dev-Fabry** [comment]
Hi
We've been talking about it for 2 or 3 weeks and there will probably never be a solution.

You can only change the interface (API) if you want updated data even when the app is closed.

Obtain the developer key pairs (you must register for free as a developer at EcoFlow and have them generated), then delete your integration, download the latest version (currently 1.1.0 final) and reinstall the integration with the Open Public API

Then you can close this issue

**Comment by vicivars** [comment]
Perfect, that's what I'm going to do, thank you very much for the solution.
