### ISSUE TITLE
Delta 2 charge pause flag

### ISSUE THREAD

**Issue by firebowl** [tolwi/hassio-ecoflow-cloud#34]
Hi,

in the diagnosis file there is "inv.chgPauseFlag": 0, but I dind't find it as configuration.
Does this option exist on Delta 2 Devices? I assume you can pause charging with this option while AC power is connected to the device.

**Comment by Technikfreak72** [comment]
I have the same question. A charging pause would be very usefull.

**Comment by tolwi** [comment]
Command to activate this can only be discovered with native app functionality, so as far as there is no such config option in the app - there is no way to implement it.
