### ISSUE TITLE
Homeassistant Public API "unknown" error (V 1.2) during setup (solved)

### ISSUE THREAD

**Issue by NoUsername10** [tolwi/hassio-ecoflow-cloud#387]
*Solved
The "unkown" error changed to "no devices" after some time.
New API key, waited, added Ecoflow devices to account again (in Ecoflow app) and it worked.

Hi.
I get this error.

I have generated a new API key, system in Europe.
Hass info:
Core 2024.11.3
Supervisor 2024.12.0
Operating System 13.2

Using the American link i get access error (('accessKey is invalid',), {}), so it seems to be something with the EU server?

![Image](https://github.com/user-attachments/assets/858153ba-c779-42d2-a293-4d0ec85ec65d)

This is the log:
`2024-12-18 14:22:42.525 ERROR (MainThread) [custom_components.ecoflow_cloud.config_flow] Unexpected exception in fetch device action
Traceback (most recent call last):
  
File "/config/custom_components/ecoflow_cloud/config_flow.py", line 272, in async_step_select_device
    devices = await self.auth.fetch_all_available_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/ecoflow_cloud/api/public_api.py", line 46, in fetch_all_available_devices
    for device in response["data"]:
                  ~~~~~~~~^^^^^^^^

KeyError: 'data'`

**Comment by AlphaZuluNRW** [comment]
@tolwi, unfortunately, that doesn't change here. It remains that “unknown” is output as an error.
