### ISSUE TITLE
Delta2 latest firmware (V1.0.0.93) removed Prio solar charging?

### ISSUE THREAD

**Issue by raphaelsavina** [tolwi/hassio-ecoflow-cloud#40]
Hi,

As anyone else seen that, with V1.0.0.93, Priority Solar charging is gone but the change log implies it should be under the new Energy Management, I cannot see it.

Thanks
Raphaël

**Comment by raphaelsavina** [comment]
It seems Prio Charging in the integration is still working but the option is missing from the Ecoflow app.
The new "Backup Reserve" option under Energy Management is supposed to be related to it, but this is not very clear on how to use it.

**Comment by tyfoon** [comment]
Was looking at the same. The release noted are also not very clear as they say in point 1: Added energy management including original solar energy prioritisation
