### ISSUE TITLE
Energy Board

### ISSUE THREAD

**Issue by rt1970** [tolwi/hassio-ecoflow-cloud#50]
Hallo!

Wie kann ich von meiner DELTA Max die MPPT-Solar-Input und Total-Output in das Energy Board vom Home Assistant als Batterie hinzufügen?

**Comment by neotigger** [comment]
Lege in der configuration.yaml ein Sensor an siehe hier 

https://www.home-assistant.io/integrations/integration/

Diese kannst du dann ins Dashboard einfügen
