### ISSUE TITLE
River 2 Max - battery main level percentage only updated when accessed via app

### ISSUE THREAD

**Issue by vedranius** [tolwi/hassio-ecoflow-cloud#58]
Hi,
I noticed that main level battery percentage only updates when I access the Ecoflow app.
And that seems to cause a whole problem in my solar configuration.
Any idea how to solve this?
Tnx!

**Comment by vedranius** [comment]
Also, Ive noticed that automations wont work until I open the Ecoflow app.

**Comment by buffcode** [comment]
See https://github.com/tolwi/hassio-ecoflow-cloud/issues/57#issuecomment-1596275221
