### ISSUE TITLE
Delta 2 Max support

### ISSUE THREAD

**Issue by cpc989** [tolwi/hassio-ecoflow-cloud#59]
can delta 2 max support be added 

device file below modified from the delta max with updated data keys from delta 2 max 

[delta2_max.txt](https://github.com/tolwi/hassio-ecoflow-cloud/files/11778686/delta2_max.txt)

**Comment by faken** [comment]
I've forked the repository and added support for Delta 2 Max: https://github.com/faken/hassio-ecoflow-cloud
I am not done with the integration and will tweak a few more details. State of Charge AC input and output power as well as variable charge power is working though.
