### ISSUE TITLE
No line hints

### ISSUE THREAD

**Issue by SerhiiZahuba** [tolwi/hassio-ecoflow-cloud#6]
If, after adding the integration, you go back to the device profile, then empty lines are displayed and without prompts. First screen before and second screen after.

![image](https://user-images.githubusercontent.com/36307887/215430954-721498d3-5046-4156-8dde-46921aaa8f94.png)
![image](https://user-images.githubusercontent.com/36307887/215431122-02f5aa3a-0b70-42e9-9f22-27a2d84ede56.png)

**Comment by tolwi** [comment]
There is no sense in modifying the existing profile - this option will be removed in the upcoming release.
