### ISSUE TITLE
Delta 2 Max

### ISSUE THREAD

**Issue by Milchbeck** [tolwi/hassio-ecoflow-cloud#60]
Please add the Delta 2 Max full support... when I change the charging level don't work

**Comment by faken** [comment]
I've forked the repository and added support for Delta 2 Max: https://github.com/faken/hassio-ecoflow-cloud

**Comment by DerBaer1986** [comment]
Hi, 
Thanks for the forked Version. It works very well.
Is it possible to get the AC Switch to Work?
USB and 12V working.
I would need it for Delta 2 Max for my automation.

Thanks you very much!
