### ISSUE TITLE
Integration gets stuck and displays old data.

### ISSUE THREAD

**Issue by rainepretorius** [tolwi/hassio-ecoflow-cloud#61]
The integration gets stuck and displays old out-of-date data. It shows the battery percentage is 20% higher than on the EcoFlow app. I need to reboot Home Assistant before this is fixed. There is also no errors in the logs or any disconnection in internet connection when this happens.
![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/64652244/c88d3173-adae-4e3f-abd4-99fcd91308a6)
![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/64652244/625fad9c-20e6-4bd4-ae8b-637495d8f867)

**Comment by tolwi** [comment]
duplicates #57
