### ISSUE TITLE
HA only receives data after the app has been started on the Smartphone

### ISSUE THREAD

**Issue by csc-arnstadt** [tolwi/hassio-ecoflow-cloud#63]
I've had the integration running for a week now and I've noticed that after the Ecoflow app has been inactive on the cell phone, no more data is read by the home assistant. If I start the Ecoflow app on my cell phone, data comes back. Of course, this is not good for data in the Energy Dashboard. I assume it's a session timeout that only starts from mobile. Can it be helped?
Best Regards!
Rainer

**Comment by faken** [comment]
See: https://github.com/tolwi/hassio-ecoflow-cloud/issues/57#issuecomment-1601218691
