### ISSUE TITLE
Allow Max Charge Level to be set below 50%

### ISSUE THREAD

**Issue by tangix** [tolwi/hassio-ecoflow-cloud#65]
Trying to implement a bi-monthly battery cycle as suggested in the docs (for my River Max at least) where the battery should be emptied to 30% and then charged to 85%. Unfortunately, with the current version (0.8.9) it is not possible to set the Charge Level lower than 50%. 
Hoping this could be fixed.

**Comment by tolwi** [comment]
It is impossible to set the Charge Level lower than 50% in a native app.

**Comment by tangix** [comment]
![5985D5BA-929A-4403-BF54-634C44C90F4C_1_102_o](https://github.com/tolwi/hassio-ecoflow-cloud/assets/1013635/12b0b627-e6f7-457d-af3c-2a75f5ec873d)
This is a RIVER Max running firmware 1.2.4.14 in the latest iOS app.

**Comment by tangix** [comment]
And yes, the unit goes down to 30% charge level before it starts charging again (indicated on the unit display).

**Comment by tolwi** [comment]
hm
set Charge level to 33% then download diagnostic dump and attach it to this issue please

**Comment by tangix** [comment]
[config_entry-ecoflow_cloud-f77d4fe9aa4e56e05717cd305f9e9c13.json.txt](https://github.com/tolwi/hassio-ecoflow-cloud/files/11907997/config_entry-ecoflow_cloud-f77d4fe9aa4e56e05717cd305f9e9c13.json.txt)

**Comment by tolwi** [comment]
v0.9.1

**Comment by tangix** [comment]
Installed 0.9.1 but unfortunately I now get these errors when changing the charge level using the slider:

```
Logger: custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt
Source: custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py:264
Integration: Ecoflow-Cloud ([documentation](https://github.com/tolwi/hassio-ecoflow-cloud), [issues](https://github.com/tolwi/hassio-ecoflow-cloud/issues))
First occurred: 07:41:56 (8 occurrences)
Last logged: 07:50:29

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 7: invalid start byte. Ignoring message and waiting for the next one.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 7: invalid start byte. Ignoring message and waiting for the next one.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 7: invalid start byte. Ignoring message and waiting for the next one.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 7: invalid start byte. Ignoring message and waiting for the next one.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 7: invalid start byte. Ignoring message and waiting for the next one.
```

Setting the value (< 50) from the iOS app I see the same value picked up in Diagnostics so App -> HA works.

**Comment by tolwi** [comment]
@tangix `UnicodeDecodeError` is not explicitly related to this functionality. If requested feature is ok - close the issue, please.
