### ISSUE TITLE
River Pro

### ISSUE THREAD

**Issue by SerhiiZahuba** [tolwi/hassio-ecoflow-cloud#7]
After adding an integration to HA and adding a device profile, it doesn't appear in the device list. If I look at the diagnostic data, I see that there is data from the device, but it does not appear as a device in HA.

**Comment by tolwi** [comment]
What is the model of that device?

**Comment by SerhiiZahuba** [comment]
River Pro

**Comment by tolwi** [comment]
It is not supported yet.
If diagnostic dump is not empty, than it can be integrated. Attach a dump and I'll add a preliminary support witch some basic sensors. 
Sometimes later will add a step-by-step manual on how to provide commands info for new devices.

**Comment by SerhiiZahuba** [comment]
[config_entry-ecoflow_cloud-194a3e4f58550cc043b36b96b2129070.json.txt](https://github.com/tolwi/hassio-ecoflow-cloud/files/10543378/config_entry-ecoflow_cloud-194a3e4f58550cc043b36b96b2129070.json.txt)

Hello. Thanks for the answer. Attached file. Check please. Thank you

**Comment by lippi00** [comment]
I've got a RIVER 2 with the same Problem - the Integration doesn't list any Devices or Entities but diagnostics are available... any chance you can help? Thanx a lot!
[config_entry-ecoflow_cloud-28b95c73ab99890file:⁄⁄⁄home⁄lippi⁄Downloads⁄config_entry-ecoflow_cloud-28b95c73ab998907ce5bdff883938fe9.json.txt7ce5bdff883938fe9.json.txt](https://github.com/tolwi/hassio-ecoflow-cloud/files/10676463/config_entry-ecoflow_cloud-28b95c73ab99890file.home.lippi.Downloads.config_entry-ecoflow_cloud-28b95c73ab998907ce5bdff883938fe9.json.txt7ce5bdff883938fe9.json.txt)

**Comment by tolwi** [comment]
> I've got a RIVER 2 with the same Problem - the Integration doesn't list any Devices or Entities but diagnostics are available... any chance you can help? Thanx a lot! [config_entry-ecoflow_cloud-28b95c73ab99890file:⁄⁄⁄home⁄lippi⁄Downloads⁄config_entry-ecoflow_cloud-28b95c73ab998907ce5bdff883938fe9.json.txt7ce5bdff883938fe9.json.txt](https://github.com/tolwi/hassio-ecoflow-cloud/files/10676463/config_entry-ecoflow_cloud-28b95c73ab99890file.home.lippi.Downloads.config_entry-ecoflow_cloud-28b95c73ab998907ce5bdff883938fe9.json.txt7ce5bdff883938fe9.json.txt)

if diag dump is full of values then yes, it can be integrated - create a separate issue for River 2.

**Comment by tolwi** [comment]
Try to fulfill this issue with info according to the following [notes](https://github.com/tolwi/hassio-ecoflow-cloud/blob/main/docs/integration.md)
