### ISSUE TITLE
Feature Request: Delta 2 Backup Reserve Setting

### ISSUE THREAD

**Issue by dannytsang** [tolwi/hassio-ecoflow-cloud#77]
I would like to be able to:
1. Turn on/off the backup reserve.
2. The amount of battery to reserve.

This is part of the Delta 2 energy management and acts almost like a UPS where it will run on battery up to the reserve battery amount expressed as a %.

E.g If you set 50% backup battery reserve then it will run on battery until it reaches 50% charge and switches to AC input (rather than battery).

![Screenshot_20230715-152836](https://github.com/tolwi/hassio-ecoflow-cloud/assets/567982/6f1e82ed-7937-4cf0-a4e7-8747fd8c3469)

**Comment by knyghtryda** [comment]
@dannytsang I added this in #74.  Looks like it's on the roadmap for release soon :)

**Comment by dannytsang** [comment]
@knyghtryda I got the update and it works! Thank you very much for adding this 🙏.

I have noticed two things with my Delta 2:
1. The reserve limit minimum in Home Assistant is 10% where as it's 5% in the app.
2. The reserve limit maximum in Home Assistant is 85% where as it's 100% in the app.

Is it possible to match the app on this and if needed, would this be a new request separate from this one?

**Comment by dannytsang** [comment]
Ignore the second point. It was because I had the max charge level set. The first point seems to be valid.

**Comment by knyghtryda** [comment]
@dannytsang haha, when I was adding this feature my minimum charge level was at 5% so my minimum reserve limit was 10%.  I can change this to update the minimum to 5%.  I'm not actually sure what happens though if say my minimum charge level is 15%.  I'm guessing that trying to set the reserve level to say 5% will just fail and it will bounce to 20% instead.

**Comment by dannytsang** [comment]
@knyghtryda that's what happened on the max charge level. It was set to 50% and when I set the backup reserve level to 100%, it would go to 50% in the app. Home Assistant would let you set the slider to 100% and then on update, go to 50%

**Comment by knyghtryda** [comment]
Done in PR #81

**Comment by dannytsang** [comment]
Confirmed working when set to 5% backup reserve. I did not test how it reacts to a lower max charge value and happy my request has been fulfilled. Thanks again @knyghtryda
