### ISSUE TITLE
Solar input

### ISSUE THREAD

**Issue by oliver989** [tolwi/hassio-ecoflow-cloud#8]
Hello

Thank you for the integration, currently using this with my Delta 2.

Would it be possible to add solar input entity?

And also it would be great if input and output was in kWh then we can add them to the energy dashboard.

**Comment by tolwi** [comment]
Hi
Have no solar input to find the right data key. Could you please identify it from the diagnostic dump - find the key by the value from mobile app (is it `pd.chgSunPower`?)
About the energy (kWh) - there are no such values provided by the device and it is not really correct to accumulate those manually.

**Comment by neotigger** [comment]
Solar Input is mppt.inWatts

**Comment by neotigger** [comment]
https://www.home-assistant.io/integrations/integration/?#energy

To convert watts to kWh, an entry in configaration.yaml is required
