### ISSUE TITLE
PowerStream

### ISSUE THREAD

**Issue by gilbert76** [tolwi/hassio-ecoflow-cloud#90]
Hello,
I have the problem that I don't have information about Battery over my PowerStream and much more information that wouldn't displayed. 
An other question is, witch Sensor say me the Power supply mode from my PowerStream? 
Best regards 
Gilbert 

![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/37107471/949162e0-6bf6-401c-9647-83e35f12c366)
![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/37107471/db26d417-a248-4550-a624-bd6d43292c16)

**Comment by mattwells** [comment]
Hi @gilbert76 sadly there is not a bug, it is a limitation of how Ecoflow made the PowerStream communicate and most of the message only have 1 or 2 fields sent. Those fields will get updated as it gets sent but that may take hours
