### ISSUE TITLE
Add new sensors for River 2 Max (and maybe others models)

### ISSUE THREAD

**Issue by chertvl** [tolwi/hassio-ecoflow-cloud#99]
Hi, Tolwi.
First of all thank you for great integration!

I have River 2 Max (-CN version) and it works great with your component!
My firmwares:  v4.1.1.56 + v.2.1.2.26(wifi).

I found some useful for me data in debug file, and I want to ask you add them as HA sensors:

in [data][params] has battery capacity info:

"bms_bmsStatus.fullCap": 17998,  -  Maximum capacity of batteries in miliAmpere*hours (mAh, may be converted in Ah by /1000).
"bms_bmsStatus.remainCap": 17995,  - current state of capacity in mAh.
"bms_bmsStatus.designCap": 20000,  - declared capacity by manufacturer
(may be useful if device need for calibration (full discharge/charge) if Full capacity is different from Design capacity, as in my 1-day new ecoflow).

"inv.acInVol": 219483,  -  "In" and: 
"inv.invOutVol": 220368,  -  "Out" AC voltage by invertor, measured in mV, may be converted in Volts by /1000  for sensor.
(useful for unstable electricity as mine in Ukraine, now I measure my AC voltage by zigbee sockets with refresh-rate ~8mins,  I think quality device as Ecoflow will be better and faster for that).

Thank you!

**Comment by chertvl** [comment]
Thank you sooo much!!!

**Comment by tolwi** [comment]
Looks like capacities are incorrect
It's 20000 in design capacity for both Delta2 and River2Max

**Comment by chertvl** [comment]
> It's 20000 in design capacity for both Delta2 and River2Max

Its okay. River 2 max has ~26V battery pack, 26 * 20Ah(20000mAh) = **~512 000 mWh (512Wh)**
Delta 2 has 51.2V battery pack,  51.2 x 20 = 1024Wh.

**Comment by chertvl** [comment]
May I ask you also to add sensor or binary_sensor for charging state?
Got it:   
"bms_emsStatus.chgState": 1,
1 - is charging, 0 - is not charging internal battery.
